// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"payment-sandbox/app/modules/invoice/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIInvoiceService creates a new instance of MockIInvoiceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIInvoiceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIInvoiceService {
	mock := &MockIInvoiceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIInvoiceService is an autogenerated mock type for the IInvoiceService type
type MockIInvoiceService struct {
	mock.Mock
}

type MockIInvoiceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIInvoiceService) EXPECT() *MockIInvoiceService_Expecter {
	return &MockIInvoiceService_Expecter{mock: &_m.Mock}
}

// CreateInvoice provides a mock function for the type MockIInvoiceService
func (_mock *MockIInvoiceService) CreateInvoice(userID string, customerName string, customerEmail string, amount float64, description string, dueDate string) (entity.Invoice, error) {
	ret := _mock.Called(userID, customerName, customerEmail, amount, description, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvoice")
	}

	var r0 entity.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, float64, string, string) (entity.Invoice, error)); ok {
		return returnFunc(userID, customerName, customerEmail, amount, description, dueDate)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, float64, string, string) entity.Invoice); ok {
		r0 = returnFunc(userID, customerName, customerEmail, amount, description, dueDate)
	} else {
		r0 = ret.Get(0).(entity.Invoice)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, float64, string, string) error); ok {
		r1 = returnFunc(userID, customerName, customerEmail, amount, description, dueDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvoiceService_CreateInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvoice'
type MockIInvoiceService_CreateInvoice_Call struct {
	*mock.Call
}

// CreateInvoice is a helper method to define mock.On call
//   - userID string
//   - customerName string
//   - customerEmail string
//   - amount float64
//   - description string
//   - dueDate string
func (_e *MockIInvoiceService_Expecter) CreateInvoice(userID interface{}, customerName interface{}, customerEmail interface{}, amount interface{}, description interface{}, dueDate interface{}) *MockIInvoiceService_CreateInvoice_Call {
	return &MockIInvoiceService_CreateInvoice_Call{Call: _e.mock.On("CreateInvoice", userID, customerName, customerEmail, amount, description, dueDate)}
}

func (_c *MockIInvoiceService_CreateInvoice_Call) Run(run func(userID string, customerName string, customerEmail string, amount float64, description string, dueDate string)) *MockIInvoiceService_CreateInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockIInvoiceService_CreateInvoice_Call) Return(invoice entity.Invoice, err error) *MockIInvoiceService_CreateInvoice_Call {
	_c.Call.Return(invoice, err)
	return _c
}

func (_c *MockIInvoiceService_CreateInvoice_Call) RunAndReturn(run func(userID string, customerName string, customerEmail string, amount float64, description string, dueDate string) (entity.Invoice, error)) *MockIInvoiceService_CreateInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// InvoiceByID provides a mock function for the type MockIInvoiceService
func (_mock *MockIInvoiceService) InvoiceByID(userID string, invoiceID string) (entity.Invoice, error) {
	ret := _mock.Called(userID, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for InvoiceByID")
	}

	var r0 entity.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (entity.Invoice, error)); ok {
		return returnFunc(userID, invoiceID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) entity.Invoice); ok {
		r0 = returnFunc(userID, invoiceID)
	} else {
		r0 = ret.Get(0).(entity.Invoice)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, invoiceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvoiceService_InvoiceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvoiceByID'
type MockIInvoiceService_InvoiceByID_Call struct {
	*mock.Call
}

// InvoiceByID is a helper method to define mock.On call
//   - userID string
//   - invoiceID string
func (_e *MockIInvoiceService_Expecter) InvoiceByID(userID interface{}, invoiceID interface{}) *MockIInvoiceService_InvoiceByID_Call {
	return &MockIInvoiceService_InvoiceByID_Call{Call: _e.mock.On("InvoiceByID", userID, invoiceID)}
}

func (_c *MockIInvoiceService_InvoiceByID_Call) Run(run func(userID string, invoiceID string)) *MockIInvoiceService_InvoiceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIInvoiceService_InvoiceByID_Call) Return(invoice entity.Invoice, err error) *MockIInvoiceService_InvoiceByID_Call {
	_c.Call.Return(invoice, err)
	return _c
}

func (_c *MockIInvoiceService_InvoiceByID_Call) RunAndReturn(run func(userID string, invoiceID string) (entity.Invoice, error)) *MockIInvoiceService_InvoiceByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListInvoices provides a mock function for the type MockIInvoiceService
func (_mock *MockIInvoiceService) ListInvoices(userID string, status string, page int, limit int) ([]entity.Invoice, int, error) {
	ret := _mock.Called(userID, status, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListInvoices")
	}

	var r0 []entity.Invoice
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) ([]entity.Invoice, int, error)); ok {
		return returnFunc(userID, status, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) []entity.Invoice); ok {
		r0 = returnFunc(userID, status, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int, int) int); ok {
		r1 = returnFunc(userID, status, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string, int, int) error); ok {
		r2 = returnFunc(userID, status, page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIInvoiceService_ListInvoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInvoices'
type MockIInvoiceService_ListInvoices_Call struct {
	*mock.Call
}

// ListInvoices is a helper method to define mock.On call
//   - userID string
//   - status string
//   - page int
//   - limit int
func (_e *MockIInvoiceService_Expecter) ListInvoices(userID interface{}, status interface{}, page interface{}, limit interface{}) *MockIInvoiceService_ListInvoices_Call {
	return &MockIInvoiceService_ListInvoices_Call{Call: _e.mock.On("ListInvoices", userID, status, page, limit)}
}

func (_c *MockIInvoiceService_ListInvoices_Call) Run(run func(userID string, status string, page int, limit int)) *MockIInvoiceService_ListInvoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIInvoiceService_ListInvoices_Call) Return(invoices []entity.Invoice, n int, err error) *MockIInvoiceService_ListInvoices_Call {
	_c.Call.Return(invoices, n, err)
	return _c
}

func (_c *MockIInvoiceService_ListInvoices_Call) RunAndReturn(run func(userID string, status string, page int, limit int) ([]entity.Invoice, int, error)) *MockIInvoiceService_ListInvoices_Call {
	_c.Call.Return(run)
	return _c
}
