// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/invoice/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateInvoice provides a mock function with given fields: userID, customerName, customerEmail, amount, description, dueDate
func (_m *MockService) CreateInvoice(userID string, customerName string, customerEmail string, amount float64, description string, dueDate string) (entity.Invoice, error) {
	ret := _m.Called(userID, customerName, customerEmail, amount, description, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvoice")
	}

	var r0 entity.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, float64, string, string) (entity.Invoice, error)); ok {
		return rf(userID, customerName, customerEmail, amount, description, dueDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, float64, string, string) entity.Invoice); ok {
		r0 = rf(userID, customerName, customerEmail, amount, description, dueDate)
	} else {
		r0 = ret.Get(0).(entity.Invoice)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, float64, string, string) error); ok {
		r1 = rf(userID, customerName, customerEmail, amount, description, dueDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvoice'
type MockService_CreateInvoice_Call struct {
	*mock.Call
}

// CreateInvoice is a helper method to define mock.On call
//   - userID string
//   - customerName string
//   - customerEmail string
//   - amount float64
//   - description string
//   - dueDate string
func (_e *MockService_Expecter) CreateInvoice(userID interface{}, customerName interface{}, customerEmail interface{}, amount interface{}, description interface{}, dueDate interface{}) *MockService_CreateInvoice_Call {
	return &MockService_CreateInvoice_Call{Call: _e.mock.On("CreateInvoice", userID, customerName, customerEmail, amount, description, dueDate)}
}

func (_c *MockService_CreateInvoice_Call) Run(run func(userID string, customerName string, customerEmail string, amount float64, description string, dueDate string)) *MockService_CreateInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(float64), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockService_CreateInvoice_Call) Return(_a0 entity.Invoice, _a1 error) *MockService_CreateInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateInvoice_Call) RunAndReturn(run func(string, string, string, float64, string, string) (entity.Invoice, error)) *MockService_CreateInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// InvoiceByID provides a mock function with given fields: userID, invoiceID
func (_m *MockService) InvoiceByID(userID string, invoiceID string) (entity.Invoice, error) {
	ret := _m.Called(userID, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for InvoiceByID")
	}

	var r0 entity.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.Invoice, error)); ok {
		return rf(userID, invoiceID)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.Invoice); ok {
		r0 = rf(userID, invoiceID)
	} else {
		r0 = ret.Get(0).(entity.Invoice)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, invoiceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_InvoiceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvoiceByID'
type MockService_InvoiceByID_Call struct {
	*mock.Call
}

// InvoiceByID is a helper method to define mock.On call
//   - userID string
//   - invoiceID string
func (_e *MockService_Expecter) InvoiceByID(userID interface{}, invoiceID interface{}) *MockService_InvoiceByID_Call {
	return &MockService_InvoiceByID_Call{Call: _e.mock.On("InvoiceByID", userID, invoiceID)}
}

func (_c *MockService_InvoiceByID_Call) Run(run func(userID string, invoiceID string)) *MockService_InvoiceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockService_InvoiceByID_Call) Return(_a0 entity.Invoice, _a1 error) *MockService_InvoiceByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_InvoiceByID_Call) RunAndReturn(run func(string, string) (entity.Invoice, error)) *MockService_InvoiceByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListInvoices provides a mock function with given fields: userID, status, page, limit
func (_m *MockService) ListInvoices(userID string, status string, page int, limit int) ([]entity.Invoice, int, error) {
	ret := _m.Called(userID, status, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListInvoices")
	}

	var r0 []entity.Invoice
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, int, int) ([]entity.Invoice, int, error)); ok {
		return rf(userID, status, page, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, int, int) []entity.Invoice); ok {
		r0 = rf(userID, status, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int, int) int); ok {
		r1 = rf(userID, status, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string, string, int, int) error); ok {
		r2 = rf(userID, status, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_ListInvoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInvoices'
type MockService_ListInvoices_Call struct {
	*mock.Call
}

// ListInvoices is a helper method to define mock.On call
//   - userID string
//   - status string
//   - page int
//   - limit int
func (_e *MockService_Expecter) ListInvoices(userID interface{}, status interface{}, page interface{}, limit interface{}) *MockService_ListInvoices_Call {
	return &MockService_ListInvoices_Call{Call: _e.mock.On("ListInvoices", userID, status, page, limit)}
}

func (_c *MockService_ListInvoices_Call) Run(run func(userID string, status string, page int, limit int)) *MockService_ListInvoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockService_ListInvoices_Call) Return(_a0 []entity.Invoice, _a1 int, _a2 error) *MockService_ListInvoices_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_ListInvoices_Call) RunAndReturn(run func(string, string, int, int) ([]entity.Invoice, int, error)) *MockService_ListInvoices_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
