// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"payment-sandbox/app/modules/invoice/models/entity"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIInvoiceRepository creates a new instance of MockIInvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIInvoiceRepository {
	mock := &MockIInvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIInvoiceRepository is an autogenerated mock type for the IInvoiceRepository type
type MockIInvoiceRepository struct {
	mock.Mock
}

type MockIInvoiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIInvoiceRepository) EXPECT() *MockIInvoiceRepository_Expecter {
	return &MockIInvoiceRepository_Expecter{mock: &_m.Mock}
}

// CreateInvoice provides a mock function for the type MockIInvoiceRepository
func (_mock *MockIInvoiceRepository) CreateInvoice(merchantID string, customerName string, customerEmail string, amount float64, description string, dueDate time.Time) (entity.Invoice, error) {
	ret := _mock.Called(merchantID, customerName, customerEmail, amount, description, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvoice")
	}

	var r0 entity.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, float64, string, time.Time) (entity.Invoice, error)); ok {
		return returnFunc(merchantID, customerName, customerEmail, amount, description, dueDate)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, float64, string, time.Time) entity.Invoice); ok {
		r0 = returnFunc(merchantID, customerName, customerEmail, amount, description, dueDate)
	} else {
		r0 = ret.Get(0).(entity.Invoice)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, float64, string, time.Time) error); ok {
		r1 = returnFunc(merchantID, customerName, customerEmail, amount, description, dueDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvoiceRepository_CreateInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvoice'
type MockIInvoiceRepository_CreateInvoice_Call struct {
	*mock.Call
}

// CreateInvoice is a helper method to define mock.On call
//   - merchantID string
//   - customerName string
//   - customerEmail string
//   - amount float64
//   - description string
//   - dueDate time.Time
func (_e *MockIInvoiceRepository_Expecter) CreateInvoice(merchantID interface{}, customerName interface{}, customerEmail interface{}, amount interface{}, description interface{}, dueDate interface{}) *MockIInvoiceRepository_CreateInvoice_Call {
	return &MockIInvoiceRepository_CreateInvoice_Call{Call: _e.mock.On("CreateInvoice", merchantID, customerName, customerEmail, amount, description, dueDate)}
}

func (_c *MockIInvoiceRepository_CreateInvoice_Call) Run(run func(merchantID string, customerName string, customerEmail string, amount float64, description string, dueDate time.Time)) *MockIInvoiceRepository_CreateInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockIInvoiceRepository_CreateInvoice_Call) Return(invoice entity.Invoice, err error) *MockIInvoiceRepository_CreateInvoice_Call {
	_c.Call.Return(invoice, err)
	return _c
}

func (_c *MockIInvoiceRepository_CreateInvoice_Call) RunAndReturn(run func(merchantID string, customerName string, customerEmail string, amount float64, description string, dueDate time.Time) (entity.Invoice, error)) *MockIInvoiceRepository_CreateInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// ListInvoices provides a mock function for the type MockIInvoiceRepository
func (_mock *MockIInvoiceRepository) ListInvoices(merchantID string, status string, options entity.ListOptions) ([]entity.Invoice, int) {
	ret := _mock.Called(merchantID, status, options)

	if len(ret) == 0 {
		panic("no return value specified for ListInvoices")
	}

	var r0 []entity.Invoice
	var r1 int
	if returnFunc, ok := ret.Get(0).(func(string, string, entity.ListOptions) ([]entity.Invoice, int)); ok {
		return returnFunc(merchantID, status, options)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, entity.ListOptions) []entity.Invoice); ok {
		r0 = returnFunc(merchantID, status, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Invoice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, entity.ListOptions) int); ok {
		r1 = returnFunc(merchantID, status, options)
	} else {
		r1 = ret.Get(1).(int)
	}
	return r0, r1
}

// MockIInvoiceRepository_ListInvoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInvoices'
type MockIInvoiceRepository_ListInvoices_Call struct {
	*mock.Call
}

// ListInvoices is a helper method to define mock.On call
//   - merchantID string
//   - status string
//   - options entity.ListOptions
func (_e *MockIInvoiceRepository_Expecter) ListInvoices(merchantID interface{}, status interface{}, options interface{}) *MockIInvoiceRepository_ListInvoices_Call {
	return &MockIInvoiceRepository_ListInvoices_Call{Call: _e.mock.On("ListInvoices", merchantID, status, options)}
}

func (_c *MockIInvoiceRepository_ListInvoices_Call) Run(run func(merchantID string, status string, options entity.ListOptions)) *MockIInvoiceRepository_ListInvoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.ListOptions
		if args[2] != nil {
			arg2 = args[2].(entity.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIInvoiceRepository_ListInvoices_Call) Return(invoices []entity.Invoice, n int) *MockIInvoiceRepository_ListInvoices_Call {
	_c.Call.Return(invoices, n)
	return _c
}

func (_c *MockIInvoiceRepository_ListInvoices_Call) RunAndReturn(run func(merchantID string, status string, options entity.ListOptions) ([]entity.Invoice, int)) *MockIInvoiceRepository_ListInvoices_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantIDByUserID provides a mock function for the type MockIInvoiceRepository
func (_mock *MockIInvoiceRepository) MerchantIDByUserID(userID string) (string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for MerchantIDByUserID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvoiceRepository_MerchantIDByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantIDByUserID'
type MockIInvoiceRepository_MerchantIDByUserID_Call struct {
	*mock.Call
}

// MerchantIDByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockIInvoiceRepository_Expecter) MerchantIDByUserID(userID interface{}) *MockIInvoiceRepository_MerchantIDByUserID_Call {
	return &MockIInvoiceRepository_MerchantIDByUserID_Call{Call: _e.mock.On("MerchantIDByUserID", userID)}
}

func (_c *MockIInvoiceRepository_MerchantIDByUserID_Call) Run(run func(userID string)) *MockIInvoiceRepository_MerchantIDByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIInvoiceRepository_MerchantIDByUserID_Call) Return(s string, err error) *MockIInvoiceRepository_MerchantIDByUserID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIInvoiceRepository_MerchantIDByUserID_Call) RunAndReturn(run func(userID string) (string, error)) *MockIInvoiceRepository_MerchantIDByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantInvoiceByID provides a mock function for the type MockIInvoiceRepository
func (_mock *MockIInvoiceRepository) MerchantInvoiceByID(invoiceID string, merchantID string) (entity.Invoice, error) {
	ret := _mock.Called(invoiceID, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for MerchantInvoiceByID")
	}

	var r0 entity.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (entity.Invoice, error)); ok {
		return returnFunc(invoiceID, merchantID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) entity.Invoice); ok {
		r0 = returnFunc(invoiceID, merchantID)
	} else {
		r0 = ret.Get(0).(entity.Invoice)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(invoiceID, merchantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIInvoiceRepository_MerchantInvoiceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantInvoiceByID'
type MockIInvoiceRepository_MerchantInvoiceByID_Call struct {
	*mock.Call
}

// MerchantInvoiceByID is a helper method to define mock.On call
//   - invoiceID string
//   - merchantID string
func (_e *MockIInvoiceRepository_Expecter) MerchantInvoiceByID(invoiceID interface{}, merchantID interface{}) *MockIInvoiceRepository_MerchantInvoiceByID_Call {
	return &MockIInvoiceRepository_MerchantInvoiceByID_Call{Call: _e.mock.On("MerchantInvoiceByID", invoiceID, merchantID)}
}

func (_c *MockIInvoiceRepository_MerchantInvoiceByID_Call) Run(run func(invoiceID string, merchantID string)) *MockIInvoiceRepository_MerchantInvoiceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIInvoiceRepository_MerchantInvoiceByID_Call) Return(invoice entity.Invoice, err error) *MockIInvoiceRepository_MerchantInvoiceByID_Call {
	_c.Call.Return(invoice, err)
	return _c
}

func (_c *MockIInvoiceRepository_MerchantInvoiceByID_Call) RunAndReturn(run func(invoiceID string, merchantID string) (entity.Invoice, error)) *MockIInvoiceRepository_MerchantInvoiceByID_Call {
	_c.Call.Return(run)
	return _c
}
