// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/invoice/models/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockInvoiceRepository is an autogenerated mock type for the InvoiceRepository type
type MockInvoiceRepository struct {
	mock.Mock
}

type MockInvoiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInvoiceRepository) EXPECT() *MockInvoiceRepository_Expecter {
	return &MockInvoiceRepository_Expecter{mock: &_m.Mock}
}

// CreateInvoice provides a mock function with given fields: merchantID, customerName, customerEmail, amount, description, dueDate
func (_m *MockInvoiceRepository) CreateInvoice(merchantID string, customerName string, customerEmail string, amount float64, description string, dueDate time.Time) (entity.Invoice, error) {
	ret := _m.Called(merchantID, customerName, customerEmail, amount, description, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvoice")
	}

	var r0 entity.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, float64, string, time.Time) (entity.Invoice, error)); ok {
		return rf(merchantID, customerName, customerEmail, amount, description, dueDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, float64, string, time.Time) entity.Invoice); ok {
		r0 = rf(merchantID, customerName, customerEmail, amount, description, dueDate)
	} else {
		r0 = ret.Get(0).(entity.Invoice)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, float64, string, time.Time) error); ok {
		r1 = rf(merchantID, customerName, customerEmail, amount, description, dueDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInvoiceRepository_CreateInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvoice'
type MockInvoiceRepository_CreateInvoice_Call struct {
	*mock.Call
}

// CreateInvoice is a helper method to define mock.On call
//   - merchantID string
//   - customerName string
//   - customerEmail string
//   - amount float64
//   - description string
//   - dueDate time.Time
func (_e *MockInvoiceRepository_Expecter) CreateInvoice(merchantID interface{}, customerName interface{}, customerEmail interface{}, amount interface{}, description interface{}, dueDate interface{}) *MockInvoiceRepository_CreateInvoice_Call {
	return &MockInvoiceRepository_CreateInvoice_Call{Call: _e.mock.On("CreateInvoice", merchantID, customerName, customerEmail, amount, description, dueDate)}
}

func (_c *MockInvoiceRepository_CreateInvoice_Call) Run(run func(merchantID string, customerName string, customerEmail string, amount float64, description string, dueDate time.Time)) *MockInvoiceRepository_CreateInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(float64), args[4].(string), args[5].(time.Time))
	})
	return _c
}

func (_c *MockInvoiceRepository_CreateInvoice_Call) Return(_a0 entity.Invoice, _a1 error) *MockInvoiceRepository_CreateInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInvoiceRepository_CreateInvoice_Call) RunAndReturn(run func(string, string, string, float64, string, time.Time) (entity.Invoice, error)) *MockInvoiceRepository_CreateInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// ListInvoices provides a mock function with given fields: merchantID, status, options
func (_m *MockInvoiceRepository) ListInvoices(merchantID string, status string, options entity.ListOptions) ([]entity.Invoice, int) {
	ret := _m.Called(merchantID, status, options)

	if len(ret) == 0 {
		panic("no return value specified for ListInvoices")
	}

	var r0 []entity.Invoice
	var r1 int
	if rf, ok := ret.Get(0).(func(string, string, entity.ListOptions) ([]entity.Invoice, int)); ok {
		return rf(merchantID, status, options)
	}
	if rf, ok := ret.Get(0).(func(string, string, entity.ListOptions) []entity.Invoice); ok {
		r0 = rf(merchantID, status, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, entity.ListOptions) int); ok {
		r1 = rf(merchantID, status, options)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// MockInvoiceRepository_ListInvoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInvoices'
type MockInvoiceRepository_ListInvoices_Call struct {
	*mock.Call
}

// ListInvoices is a helper method to define mock.On call
//   - merchantID string
//   - status string
//   - options entity.ListOptions
func (_e *MockInvoiceRepository_Expecter) ListInvoices(merchantID interface{}, status interface{}, options interface{}) *MockInvoiceRepository_ListInvoices_Call {
	return &MockInvoiceRepository_ListInvoices_Call{Call: _e.mock.On("ListInvoices", merchantID, status, options)}
}

func (_c *MockInvoiceRepository_ListInvoices_Call) Run(run func(merchantID string, status string, options entity.ListOptions)) *MockInvoiceRepository_ListInvoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(entity.ListOptions))
	})
	return _c
}

func (_c *MockInvoiceRepository_ListInvoices_Call) Return(_a0 []entity.Invoice, _a1 int) *MockInvoiceRepository_ListInvoices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInvoiceRepository_ListInvoices_Call) RunAndReturn(run func(string, string, entity.ListOptions) ([]entity.Invoice, int)) *MockInvoiceRepository_ListInvoices_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantIDByUserID provides a mock function with given fields: userID
func (_m *MockInvoiceRepository) MerchantIDByUserID(userID string) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for MerchantIDByUserID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInvoiceRepository_MerchantIDByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantIDByUserID'
type MockInvoiceRepository_MerchantIDByUserID_Call struct {
	*mock.Call
}

// MerchantIDByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockInvoiceRepository_Expecter) MerchantIDByUserID(userID interface{}) *MockInvoiceRepository_MerchantIDByUserID_Call {
	return &MockInvoiceRepository_MerchantIDByUserID_Call{Call: _e.mock.On("MerchantIDByUserID", userID)}
}

func (_c *MockInvoiceRepository_MerchantIDByUserID_Call) Run(run func(userID string)) *MockInvoiceRepository_MerchantIDByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockInvoiceRepository_MerchantIDByUserID_Call) Return(_a0 string, _a1 error) *MockInvoiceRepository_MerchantIDByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInvoiceRepository_MerchantIDByUserID_Call) RunAndReturn(run func(string) (string, error)) *MockInvoiceRepository_MerchantIDByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantInvoiceByID provides a mock function with given fields: invoiceID, merchantID
func (_m *MockInvoiceRepository) MerchantInvoiceByID(invoiceID string, merchantID string) (entity.Invoice, error) {
	ret := _m.Called(invoiceID, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for MerchantInvoiceByID")
	}

	var r0 entity.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.Invoice, error)); ok {
		return rf(invoiceID, merchantID)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.Invoice); ok {
		r0 = rf(invoiceID, merchantID)
	} else {
		r0 = ret.Get(0).(entity.Invoice)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(invoiceID, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInvoiceRepository_MerchantInvoiceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantInvoiceByID'
type MockInvoiceRepository_MerchantInvoiceByID_Call struct {
	*mock.Call
}

// MerchantInvoiceByID is a helper method to define mock.On call
//   - invoiceID string
//   - merchantID string
func (_e *MockInvoiceRepository_Expecter) MerchantInvoiceByID(invoiceID interface{}, merchantID interface{}) *MockInvoiceRepository_MerchantInvoiceByID_Call {
	return &MockInvoiceRepository_MerchantInvoiceByID_Call{Call: _e.mock.On("MerchantInvoiceByID", invoiceID, merchantID)}
}

func (_c *MockInvoiceRepository_MerchantInvoiceByID_Call) Run(run func(invoiceID string, merchantID string)) *MockInvoiceRepository_MerchantInvoiceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockInvoiceRepository_MerchantInvoiceByID_Call) Return(_a0 entity.Invoice, _a1 error) *MockInvoiceRepository_MerchantInvoiceByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInvoiceRepository_MerchantInvoiceByID_Call) RunAndReturn(run func(string, string) (entity.Invoice, error)) *MockInvoiceRepository_MerchantInvoiceByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInvoiceRepository creates a new instance of MockInvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvoiceRepository {
	mock := &MockInvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
