// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "payment-sandbox/app/modules/merchants/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockIMerchantsRepository is an autogenerated mock type for the IMerchantsRepository type
type MockIMerchantsRepository struct {
	mock.Mock
}

type MockIMerchantsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMerchantsRepository) EXPECT() *MockIMerchantsRepository_Expecter {
	return &MockIMerchantsRepository_Expecter{mock: &_m.Mock}
}

// ListMerchants provides a mock function with given fields: ctx, search, page, limit
func (_m *MockIMerchantsRepository) ListMerchants(ctx context.Context, search string, page int, limit int) ([]entity.MerchantSummary, int, error) {
	ret := _m.Called(ctx, search, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListMerchants")
	}

	var r0 []entity.MerchantSummary
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]entity.MerchantSummary, int, error)); ok {
		return rf(ctx, search, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []entity.MerchantSummary); ok {
		r0 = rf(ctx, search, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.MerchantSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, search, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, search, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIMerchantsRepository_ListMerchants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMerchants'
type MockIMerchantsRepository_ListMerchants_Call struct {
	*mock.Call
}

// ListMerchants is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - page int
//   - limit int
func (_e *MockIMerchantsRepository_Expecter) ListMerchants(ctx interface{}, search interface{}, page interface{}, limit interface{}) *MockIMerchantsRepository_ListMerchants_Call {
	return &MockIMerchantsRepository_ListMerchants_Call{Call: _e.mock.On("ListMerchants", ctx, search, page, limit)}
}

func (_c *MockIMerchantsRepository_ListMerchants_Call) Run(run func(ctx context.Context, search string, page int, limit int)) *MockIMerchantsRepository_ListMerchants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIMerchantsRepository_ListMerchants_Call) Return(_a0 []entity.MerchantSummary, _a1 int, _a2 error) *MockIMerchantsRepository_ListMerchants_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIMerchantsRepository_ListMerchants_Call) RunAndReturn(run func(context.Context, string, int, int) ([]entity.MerchantSummary, int, error)) *MockIMerchantsRepository_ListMerchants_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIMerchantsRepository creates a new instance of MockIMerchantsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMerchantsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMerchantsRepository {
	mock := &MockIMerchantsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
