// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/refund/models/entity"
	modelsentity "payment-sandbox/app/modules/wallet/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockIRefundService is an autogenerated mock type for the IRefundService type
type MockIRefundService struct {
	mock.Mock
}

type MockIRefundService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRefundService) EXPECT() *MockIRefundService_Expecter {
	return &MockIRefundService_Expecter{mock: &_m.Mock}
}

// ListRefunds provides a mock function with given fields: status
func (_m *MockIRefundService) ListRefunds(status string) []entity.Refund {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for ListRefunds")
	}

	var r0 []entity.Refund
	if rf, ok := ret.Get(0).(func(string) []entity.Refund); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Refund)
		}
	}

	return r0
}

// MockIRefundService_ListRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRefunds'
type MockIRefundService_ListRefunds_Call struct {
	*mock.Call
}

// ListRefunds is a helper method to define mock.On call
//   - status string
func (_e *MockIRefundService_Expecter) ListRefunds(status interface{}) *MockIRefundService_ListRefunds_Call {
	return &MockIRefundService_ListRefunds_Call{Call: _e.mock.On("ListRefunds", status)}
}

func (_c *MockIRefundService_ListRefunds_Call) Run(run func(status string)) *MockIRefundService_ListRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIRefundService_ListRefunds_Call) Return(_a0 []entity.Refund) *MockIRefundService_ListRefunds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRefundService_ListRefunds_Call) RunAndReturn(run func(string) []entity.Refund) *MockIRefundService_ListRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantListRefunds provides a mock function with given fields: userID, status
func (_m *MockIRefundService) MerchantListRefunds(userID string, status string) []entity.Refund {
	ret := _m.Called(userID, status)

	if len(ret) == 0 {
		panic("no return value specified for MerchantListRefunds")
	}

	var r0 []entity.Refund
	if rf, ok := ret.Get(0).(func(string, string) []entity.Refund); ok {
		r0 = rf(userID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Refund)
		}
	}

	return r0
}

// MockIRefundService_MerchantListRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantListRefunds'
type MockIRefundService_MerchantListRefunds_Call struct {
	*mock.Call
}

// MerchantListRefunds is a helper method to define mock.On call
//   - userID string
//   - status string
func (_e *MockIRefundService_Expecter) MerchantListRefunds(userID interface{}, status interface{}) *MockIRefundService_MerchantListRefunds_Call {
	return &MockIRefundService_MerchantListRefunds_Call{Call: _e.mock.On("MerchantListRefunds", userID, status)}
}

func (_c *MockIRefundService_MerchantListRefunds_Call) Run(run func(userID string, status string)) *MockIRefundService_MerchantListRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIRefundService_MerchantListRefunds_Call) Return(_a0 []entity.Refund) *MockIRefundService_MerchantListRefunds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRefundService_MerchantListRefunds_Call) RunAndReturn(run func(string, string) []entity.Refund) *MockIRefundService_MerchantListRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessRefund provides a mock function with given fields: refundID, status
func (_m *MockIRefundService) ProcessRefund(refundID string, status string) (entity.Refund, modelsentity.Merchant, error) {
	ret := _m.Called(refundID, status)

	if len(ret) == 0 {
		panic("no return value specified for ProcessRefund")
	}

	var r0 entity.Refund
	var r1 modelsentity.Merchant
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.Refund, modelsentity.Merchant, error)); ok {
		return rf(refundID, status)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.Refund); ok {
		r0 = rf(refundID, status)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, string) modelsentity.Merchant); ok {
		r1 = rf(refundID, status)
	} else {
		r1 = ret.Get(1).(modelsentity.Merchant)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(refundID, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIRefundService_ProcessRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessRefund'
type MockIRefundService_ProcessRefund_Call struct {
	*mock.Call
}

// ProcessRefund is a helper method to define mock.On call
//   - refundID string
//   - status string
func (_e *MockIRefundService_Expecter) ProcessRefund(refundID interface{}, status interface{}) *MockIRefundService_ProcessRefund_Call {
	return &MockIRefundService_ProcessRefund_Call{Call: _e.mock.On("ProcessRefund", refundID, status)}
}

func (_c *MockIRefundService_ProcessRefund_Call) Run(run func(refundID string, status string)) *MockIRefundService_ProcessRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIRefundService_ProcessRefund_Call) Return(_a0 entity.Refund, _a1 modelsentity.Merchant, _a2 error) *MockIRefundService_ProcessRefund_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIRefundService_ProcessRefund_Call) RunAndReturn(run func(string, string) (entity.Refund, modelsentity.Merchant, error)) *MockIRefundService_ProcessRefund_Call {
	_c.Call.Return(run)
	return _c
}

// RequestRefund provides a mock function with given fields: userID, invoiceID, reason
func (_m *MockIRefundService) RequestRefund(userID string, invoiceID string, reason string) (entity.Refund, error) {
	ret := _m.Called(userID, invoiceID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RequestRefund")
	}

	var r0 entity.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (entity.Refund, error)); ok {
		return rf(userID, invoiceID, reason)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) entity.Refund); ok {
		r0 = rf(userID, invoiceID, reason)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(userID, invoiceID, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRefundService_RequestRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestRefund'
type MockIRefundService_RequestRefund_Call struct {
	*mock.Call
}

// RequestRefund is a helper method to define mock.On call
//   - userID string
//   - invoiceID string
//   - reason string
func (_e *MockIRefundService_Expecter) RequestRefund(userID interface{}, invoiceID interface{}, reason interface{}) *MockIRefundService_RequestRefund_Call {
	return &MockIRefundService_RequestRefund_Call{Call: _e.mock.On("RequestRefund", userID, invoiceID, reason)}
}

func (_c *MockIRefundService_RequestRefund_Call) Run(run func(userID string, invoiceID string, reason string)) *MockIRefundService_RequestRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIRefundService_RequestRefund_Call) Return(_a0 entity.Refund, _a1 error) *MockIRefundService_RequestRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRefundService_RequestRefund_Call) RunAndReturn(run func(string, string, string) (entity.Refund, error)) *MockIRefundService_RequestRefund_Call {
	_c.Call.Return(run)
	return _c
}

// ReviewRefund provides a mock function with given fields: refundID, decision
func (_m *MockIRefundService) ReviewRefund(refundID string, decision string) (entity.Refund, error) {
	ret := _m.Called(refundID, decision)

	if len(ret) == 0 {
		panic("no return value specified for ReviewRefund")
	}

	var r0 entity.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.Refund, error)); ok {
		return rf(refundID, decision)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.Refund); ok {
		r0 = rf(refundID, decision)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(refundID, decision)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRefundService_ReviewRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReviewRefund'
type MockIRefundService_ReviewRefund_Call struct {
	*mock.Call
}

// ReviewRefund is a helper method to define mock.On call
//   - refundID string
//   - decision string
func (_e *MockIRefundService_Expecter) ReviewRefund(refundID interface{}, decision interface{}) *MockIRefundService_ReviewRefund_Call {
	return &MockIRefundService_ReviewRefund_Call{Call: _e.mock.On("ReviewRefund", refundID, decision)}
}

func (_c *MockIRefundService_ReviewRefund_Call) Run(run func(refundID string, decision string)) *MockIRefundService_ReviewRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIRefundService_ReviewRefund_Call) Return(_a0 entity.Refund, _a1 error) *MockIRefundService_ReviewRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRefundService_ReviewRefund_Call) RunAndReturn(run func(string, string) (entity.Refund, error)) *MockIRefundService_ReviewRefund_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRefundService creates a new instance of MockIRefundService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRefundService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRefundService {
	mock := &MockIRefundService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
