// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"payment-sandbox/app/modules/refund/models/entity"
	entity0 "payment-sandbox/app/modules/wallet/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIRefundService creates a new instance of MockIRefundService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRefundService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRefundService {
	mock := &MockIRefundService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRefundService is an autogenerated mock type for the IRefundService type
type MockIRefundService struct {
	mock.Mock
}

type MockIRefundService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRefundService) EXPECT() *MockIRefundService_Expecter {
	return &MockIRefundService_Expecter{mock: &_m.Mock}
}

// ListRefunds provides a mock function for the type MockIRefundService
func (_mock *MockIRefundService) ListRefunds(status string) []entity.Refund {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for ListRefunds")
	}

	var r0 []entity.Refund
	if returnFunc, ok := ret.Get(0).(func(string) []entity.Refund); ok {
		r0 = returnFunc(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Refund)
		}
	}
	return r0
}

// MockIRefundService_ListRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRefunds'
type MockIRefundService_ListRefunds_Call struct {
	*mock.Call
}

// ListRefunds is a helper method to define mock.On call
//   - status string
func (_e *MockIRefundService_Expecter) ListRefunds(status interface{}) *MockIRefundService_ListRefunds_Call {
	return &MockIRefundService_ListRefunds_Call{Call: _e.mock.On("ListRefunds", status)}
}

func (_c *MockIRefundService_ListRefunds_Call) Run(run func(status string)) *MockIRefundService_ListRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRefundService_ListRefunds_Call) Return(refunds []entity.Refund) *MockIRefundService_ListRefunds_Call {
	_c.Call.Return(refunds)
	return _c
}

func (_c *MockIRefundService_ListRefunds_Call) RunAndReturn(run func(status string) []entity.Refund) *MockIRefundService_ListRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessRefund provides a mock function for the type MockIRefundService
func (_mock *MockIRefundService) ProcessRefund(refundID string, status string) (entity.Refund, entity0.Merchant, error) {
	ret := _mock.Called(refundID, status)

	if len(ret) == 0 {
		panic("no return value specified for ProcessRefund")
	}

	var r0 entity.Refund
	var r1 entity0.Merchant
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (entity.Refund, entity0.Merchant, error)); ok {
		return returnFunc(refundID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) entity.Refund); ok {
		r0 = returnFunc(refundID, status)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) entity0.Merchant); ok {
		r1 = returnFunc(refundID, status)
	} else {
		r1 = ret.Get(1).(entity0.Merchant)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(refundID, status)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIRefundService_ProcessRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessRefund'
type MockIRefundService_ProcessRefund_Call struct {
	*mock.Call
}

// ProcessRefund is a helper method to define mock.On call
//   - refundID string
//   - status string
func (_e *MockIRefundService_Expecter) ProcessRefund(refundID interface{}, status interface{}) *MockIRefundService_ProcessRefund_Call {
	return &MockIRefundService_ProcessRefund_Call{Call: _e.mock.On("ProcessRefund", refundID, status)}
}

func (_c *MockIRefundService_ProcessRefund_Call) Run(run func(refundID string, status string)) *MockIRefundService_ProcessRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRefundService_ProcessRefund_Call) Return(refund entity.Refund, merchant entity0.Merchant, err error) *MockIRefundService_ProcessRefund_Call {
	_c.Call.Return(refund, merchant, err)
	return _c
}

func (_c *MockIRefundService_ProcessRefund_Call) RunAndReturn(run func(refundID string, status string) (entity.Refund, entity0.Merchant, error)) *MockIRefundService_ProcessRefund_Call {
	_c.Call.Return(run)
	return _c
}

// RequestRefund provides a mock function for the type MockIRefundService
func (_mock *MockIRefundService) RequestRefund(userID string, paymentIntentID string, reason string) (entity.Refund, error) {
	ret := _mock.Called(userID, paymentIntentID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RequestRefund")
	}

	var r0 entity.Refund
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (entity.Refund, error)); ok {
		return returnFunc(userID, paymentIntentID, reason)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) entity.Refund); ok {
		r0 = returnFunc(userID, paymentIntentID, reason)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(userID, paymentIntentID, reason)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRefundService_RequestRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestRefund'
type MockIRefundService_RequestRefund_Call struct {
	*mock.Call
}

// RequestRefund is a helper method to define mock.On call
//   - userID string
//   - paymentIntentID string
//   - reason string
func (_e *MockIRefundService_Expecter) RequestRefund(userID interface{}, paymentIntentID interface{}, reason interface{}) *MockIRefundService_RequestRefund_Call {
	return &MockIRefundService_RequestRefund_Call{Call: _e.mock.On("RequestRefund", userID, paymentIntentID, reason)}
}

func (_c *MockIRefundService_RequestRefund_Call) Run(run func(userID string, paymentIntentID string, reason string)) *MockIRefundService_RequestRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIRefundService_RequestRefund_Call) Return(refund entity.Refund, err error) *MockIRefundService_RequestRefund_Call {
	_c.Call.Return(refund, err)
	return _c
}

func (_c *MockIRefundService_RequestRefund_Call) RunAndReturn(run func(userID string, paymentIntentID string, reason string) (entity.Refund, error)) *MockIRefundService_RequestRefund_Call {
	_c.Call.Return(run)
	return _c
}

// ReviewRefund provides a mock function for the type MockIRefundService
func (_mock *MockIRefundService) ReviewRefund(refundID string, decision string) (entity.Refund, error) {
	ret := _mock.Called(refundID, decision)

	if len(ret) == 0 {
		panic("no return value specified for ReviewRefund")
	}

	var r0 entity.Refund
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (entity.Refund, error)); ok {
		return returnFunc(refundID, decision)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) entity.Refund); ok {
		r0 = returnFunc(refundID, decision)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(refundID, decision)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRefundService_ReviewRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReviewRefund'
type MockIRefundService_ReviewRefund_Call struct {
	*mock.Call
}

// ReviewRefund is a helper method to define mock.On call
//   - refundID string
//   - decision string
func (_e *MockIRefundService_Expecter) ReviewRefund(refundID interface{}, decision interface{}) *MockIRefundService_ReviewRefund_Call {
	return &MockIRefundService_ReviewRefund_Call{Call: _e.mock.On("ReviewRefund", refundID, decision)}
}

func (_c *MockIRefundService_ReviewRefund_Call) Run(run func(refundID string, decision string)) *MockIRefundService_ReviewRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRefundService_ReviewRefund_Call) Return(refund entity.Refund, err error) *MockIRefundService_ReviewRefund_Call {
	_c.Call.Return(refund, err)
	return _c
}

func (_c *MockIRefundService_ReviewRefund_Call) RunAndReturn(run func(refundID string, decision string) (entity.Refund, error)) *MockIRefundService_ReviewRefund_Call {
	_c.Call.Return(run)
	return _c
}
