// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/refund/models/entity"
	modelsentity "payment-sandbox/app/modules/wallet/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ListRefunds provides a mock function with given fields: status
func (_m *MockService) ListRefunds(status string) []entity.Refund {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for ListRefunds")
	}

	var r0 []entity.Refund
	if rf, ok := ret.Get(0).(func(string) []entity.Refund); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Refund)
		}
	}

	return r0
}

// MockService_ListRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRefunds'
type MockService_ListRefunds_Call struct {
	*mock.Call
}

// ListRefunds is a helper method to define mock.On call
//   - status string
func (_e *MockService_Expecter) ListRefunds(status interface{}) *MockService_ListRefunds_Call {
	return &MockService_ListRefunds_Call{Call: _e.mock.On("ListRefunds", status)}
}

func (_c *MockService_ListRefunds_Call) Run(run func(status string)) *MockService_ListRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_ListRefunds_Call) Return(_a0 []entity.Refund) *MockService_ListRefunds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ListRefunds_Call) RunAndReturn(run func(string) []entity.Refund) *MockService_ListRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessRefund provides a mock function with given fields: refundID, status
func (_m *MockService) ProcessRefund(refundID string, status string) (entity.Refund, modelsentity.Merchant, error) {
	ret := _m.Called(refundID, status)

	if len(ret) == 0 {
		panic("no return value specified for ProcessRefund")
	}

	var r0 entity.Refund
	var r1 modelsentity.Merchant
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.Refund, modelsentity.Merchant, error)); ok {
		return rf(refundID, status)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.Refund); ok {
		r0 = rf(refundID, status)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, string) modelsentity.Merchant); ok {
		r1 = rf(refundID, status)
	} else {
		r1 = ret.Get(1).(modelsentity.Merchant)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(refundID, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_ProcessRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessRefund'
type MockService_ProcessRefund_Call struct {
	*mock.Call
}

// ProcessRefund is a helper method to define mock.On call
//   - refundID string
//   - status string
func (_e *MockService_Expecter) ProcessRefund(refundID interface{}, status interface{}) *MockService_ProcessRefund_Call {
	return &MockService_ProcessRefund_Call{Call: _e.mock.On("ProcessRefund", refundID, status)}
}

func (_c *MockService_ProcessRefund_Call) Run(run func(refundID string, status string)) *MockService_ProcessRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockService_ProcessRefund_Call) Return(_a0 entity.Refund, _a1 modelsentity.Merchant, _a2 error) *MockService_ProcessRefund_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_ProcessRefund_Call) RunAndReturn(run func(string, string) (entity.Refund, modelsentity.Merchant, error)) *MockService_ProcessRefund_Call {
	_c.Call.Return(run)
	return _c
}

// RequestRefund provides a mock function with given fields: userID, paymentIntentID, reason
func (_m *MockService) RequestRefund(userID string, paymentIntentID string, reason string) (entity.Refund, error) {
	ret := _m.Called(userID, paymentIntentID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RequestRefund")
	}

	var r0 entity.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (entity.Refund, error)); ok {
		return rf(userID, paymentIntentID, reason)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) entity.Refund); ok {
		r0 = rf(userID, paymentIntentID, reason)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(userID, paymentIntentID, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RequestRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestRefund'
type MockService_RequestRefund_Call struct {
	*mock.Call
}

// RequestRefund is a helper method to define mock.On call
//   - userID string
//   - paymentIntentID string
//   - reason string
func (_e *MockService_Expecter) RequestRefund(userID interface{}, paymentIntentID interface{}, reason interface{}) *MockService_RequestRefund_Call {
	return &MockService_RequestRefund_Call{Call: _e.mock.On("RequestRefund", userID, paymentIntentID, reason)}
}

func (_c *MockService_RequestRefund_Call) Run(run func(userID string, paymentIntentID string, reason string)) *MockService_RequestRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_RequestRefund_Call) Return(_a0 entity.Refund, _a1 error) *MockService_RequestRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RequestRefund_Call) RunAndReturn(run func(string, string, string) (entity.Refund, error)) *MockService_RequestRefund_Call {
	_c.Call.Return(run)
	return _c
}

// ReviewRefund provides a mock function with given fields: refundID, decision
func (_m *MockService) ReviewRefund(refundID string, decision string) (entity.Refund, error) {
	ret := _m.Called(refundID, decision)

	if len(ret) == 0 {
		panic("no return value specified for ReviewRefund")
	}

	var r0 entity.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.Refund, error)); ok {
		return rf(refundID, decision)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.Refund); ok {
		r0 = rf(refundID, decision)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(refundID, decision)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ReviewRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReviewRefund'
type MockService_ReviewRefund_Call struct {
	*mock.Call
}

// ReviewRefund is a helper method to define mock.On call
//   - refundID string
//   - decision string
func (_e *MockService_Expecter) ReviewRefund(refundID interface{}, decision interface{}) *MockService_ReviewRefund_Call {
	return &MockService_ReviewRefund_Call{Call: _e.mock.On("ReviewRefund", refundID, decision)}
}

func (_c *MockService_ReviewRefund_Call) Run(run func(refundID string, decision string)) *MockService_ReviewRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockService_ReviewRefund_Call) Return(_a0 entity.Refund, _a1 error) *MockService_ReviewRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ReviewRefund_Call) RunAndReturn(run func(string, string) (entity.Refund, error)) *MockService_ReviewRefund_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
