with-expecter: true
inpackage: false
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

packages:
  payment-sandbox/app/modules/auth/repositories:
    interfaces:
      AuthRepository:
  payment-sandbox/app/modules/admin/repositories:
    interfaces:
      AdminRepository:
  payment-sandbox/app/modules/wallet/repositories:
    interfaces:
      WalletRepository:
  payment-sandbox/app/modules/invoice/repositories:
    interfaces:
      InvoiceRepository:
  payment-sandbox/app/modules/payment/repositories:
    interfaces:
      PaymentRepository:
  payment-sandbox/app/modules/refund/repositories:
    interfaces:
      RefundRepository:
  payment-sandbox/app/shared/journeylog:
    interfaces:
      JourneyLogger:
  payment-sandbox/app/modules/auth/handlers:
    interfaces:
      AuthService:
  payment-sandbox/app/modules/admin/handlers:
    interfaces:
      AdminService:
  payment-sandbox/app/modules/wallet/handlers:
    interfaces:
      WalletService:
  payment-sandbox/app/modules/invoice/handlers:
    interfaces:
      InvoiceService:
  payment-sandbox/app/modules/payment/handlers:
    interfaces:
      PaymentService:
  payment-sandbox/app/modules/refund/handlers:
    interfaces:
      RefundService:
  payment-sandbox/app/modules/auth/services:
    interfaces:
      Service:
  payment-sandbox/app/modules/admin/services:
    interfaces:
      Service:
  payment-sandbox/app/modules/wallet/services:
    interfaces:
      Service:
  payment-sandbox/app/modules/invoice/services:
    interfaces:
      Service:
  payment-sandbox/app/modules/payment/services:
    interfaces:
      Service:
  payment-sandbox/app/modules/refund/services:
    interfaces:
      Service:
