with-expecter: true
inpackage: false
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

packages:
  payment-sandbox/app/modules/auth/repositories:
    interfaces:
      IAuthRepository:
  payment-sandbox/app/modules/admin/repositories:
    interfaces:
      IAdminRepository:
  payment-sandbox/app/modules/wallet/repositories:
    interfaces:
      IWalletRepository:
  payment-sandbox/app/modules/invoice/repositories:
    interfaces:
      IInvoiceRepository:
  payment-sandbox/app/modules/payment/repositories:
    interfaces:
      IPaymentRepository:
  payment-sandbox/app/modules/refund/repositories:
    interfaces:
      IRefundRepository:
  payment-sandbox/app/modules/oauth2/repositories:
    interfaces:
      IOAuth2Repository:
  payment-sandbox/app/shared/journeylog:
    interfaces:
      IJourneyLogger:
  payment-sandbox/app/modules/auth/services:
    interfaces:
      IAuthService:
  payment-sandbox/app/modules/admin/services:
    interfaces:
      IAdminService:
  payment-sandbox/app/modules/wallet/services:
    interfaces:
      IWalletService:
  payment-sandbox/app/modules/invoice/services:
    interfaces:
      IInvoiceService:
  payment-sandbox/app/modules/payment/services:
    interfaces:
      IPaymentService:
  payment-sandbox/app/modules/refund/services:
    interfaces:
      IRefundService:
  payment-sandbox/app/modules/oauth2/services:
    interfaces:
      IOAuth2Service:
