services:
  postgres:
    image: postgres:18.3-alpine3.23
    container_name: payment-sandbox-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: payment_sandbox
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d payment_sandbox" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./misc/init-sql:/docker-entrypoint-initdb.d
  mongodb:
    image: mongo:8.0.14-rc0-noble
    container_name: payment-sandbox-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: payment_sandbox
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
    volumes:
      - ./misc/init-mongo/mongo.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --host 127.0.0.1 --port 27017 --username \"$$MONGO_INITDB_ROOT_USERNAME\" --password \"$$MONGO_INITDB_ROOT_PASSWORD\" --authenticationDatabase admin --quiet --eval 'db.adminCommand(\"ping\").ok' | grep -q 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
  redis:
    image: redis:7-alpine
    container_name: payment-sandbox-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb
    container_name: payment-sandbox-pgweb
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://root:secretpassword@postgres:5432/payment_sandbox?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: docker
    container_name: payment-sandbox-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mongo-data:
