// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"payment-sandbox/app/modules/admin/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIAdminService creates a new instance of MockIAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAdminService {
	mock := &MockIAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAdminService is an autogenerated mock type for the IAdminService type
type MockIAdminService struct {
	mock.Mock
}

type MockIAdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAdminService) EXPECT() *MockIAdminService_Expecter {
	return &MockIAdminService_Expecter{mock: &_m.Mock}
}

// Stats provides a mock function for the type MockIAdminService
func (_mock *MockIAdminService) Stats(merchantID string, startDate string, endDate string) (entity.DashboardStats, error) {
	ret := _mock.Called(merchantID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 entity.DashboardStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (entity.DashboardStats, error)); ok {
		return returnFunc(merchantID, startDate, endDate)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) entity.DashboardStats); ok {
		r0 = returnFunc(merchantID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(entity.DashboardStats)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(merchantID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAdminService_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockIAdminService_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - merchantID string
//   - startDate string
//   - endDate string
func (_e *MockIAdminService_Expecter) Stats(merchantID interface{}, startDate interface{}, endDate interface{}) *MockIAdminService_Stats_Call {
	return &MockIAdminService_Stats_Call{Call: _e.mock.On("Stats", merchantID, startDate, endDate)}
}

func (_c *MockIAdminService_Stats_Call) Run(run func(merchantID string, startDate string, endDate string)) *MockIAdminService_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAdminService_Stats_Call) Return(dashboardStats entity.DashboardStats, err error) *MockIAdminService_Stats_Call {
	_c.Call.Return(dashboardStats, err)
	return _c
}

func (_c *MockIAdminService_Stats_Call) RunAndReturn(run func(merchantID string, startDate string, endDate string) (entity.DashboardStats, error)) *MockIAdminService_Stats_Call {
	_c.Call.Return(run)
	return _c
}
