// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/oauth2/models/entity"
	services "payment-sandbox/app/modules/oauth2/services"
	modelsentity "payment-sandbox/app/modules/users/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockIOAuth2Service is an autogenerated mock type for the IOAuth2Service type
type MockIOAuth2Service struct {
	mock.Mock
}

type MockIOAuth2Service_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOAuth2Service) EXPECT() *MockIOAuth2Service_Expecter {
	return &MockIOAuth2Service_Expecter{mock: &_m.Mock}
}

// DeleteClient provides a mock function with given fields: clientID, ownerID
func (_m *MockIOAuth2Service) DeleteClient(clientID string, ownerID string) error {
	ret := _m.Called(clientID, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(clientID, ownerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOAuth2Service_DeleteClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClient'
type MockIOAuth2Service_DeleteClient_Call struct {
	*mock.Call
}

// DeleteClient is a helper method to define mock.On call
//   - clientID string
//   - ownerID string
func (_e *MockIOAuth2Service_Expecter) DeleteClient(clientID interface{}, ownerID interface{}) *MockIOAuth2Service_DeleteClient_Call {
	return &MockIOAuth2Service_DeleteClient_Call{Call: _e.mock.On("DeleteClient", clientID, ownerID)}
}

func (_c *MockIOAuth2Service_DeleteClient_Call) Run(run func(clientID string, ownerID string)) *MockIOAuth2Service_DeleteClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_DeleteClient_Call) Return(_a0 error) *MockIOAuth2Service_DeleteClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOAuth2Service_DeleteClient_Call) RunAndReturn(run func(string, string) error) *MockIOAuth2Service_DeleteClient_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeAuthCode provides a mock function with given fields: code, clientID, redirectURI
func (_m *MockIOAuth2Service) ExchangeAuthCode(code string, clientID string, redirectURI string) (entity.AuthorizationCode, error) {
	ret := _m.Called(code, clientID, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeAuthCode")
	}

	var r0 entity.AuthorizationCode
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (entity.AuthorizationCode, error)); ok {
		return rf(code, clientID, redirectURI)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) entity.AuthorizationCode); ok {
		r0 = rf(code, clientID, redirectURI)
	} else {
		r0 = ret.Get(0).(entity.AuthorizationCode)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(code, clientID, redirectURI)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_ExchangeAuthCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeAuthCode'
type MockIOAuth2Service_ExchangeAuthCode_Call struct {
	*mock.Call
}

// ExchangeAuthCode is a helper method to define mock.On call
//   - code string
//   - clientID string
//   - redirectURI string
func (_e *MockIOAuth2Service_Expecter) ExchangeAuthCode(code interface{}, clientID interface{}, redirectURI interface{}) *MockIOAuth2Service_ExchangeAuthCode_Call {
	return &MockIOAuth2Service_ExchangeAuthCode_Call{Call: _e.mock.On("ExchangeAuthCode", code, clientID, redirectURI)}
}

func (_c *MockIOAuth2Service_ExchangeAuthCode_Call) Run(run func(code string, clientID string, redirectURI string)) *MockIOAuth2Service_ExchangeAuthCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_ExchangeAuthCode_Call) Return(_a0 entity.AuthorizationCode, _a1 error) *MockIOAuth2Service_ExchangeAuthCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_ExchangeAuthCode_Call) RunAndReturn(run func(string, string, string) (entity.AuthorizationCode, error)) *MockIOAuth2Service_ExchangeAuthCode_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeRefreshToken provides a mock function with given fields: token, clientID
func (_m *MockIOAuth2Service) ExchangeRefreshToken(token string, clientID string) (entity.RefreshToken, error) {
	ret := _m.Called(token, clientID)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeRefreshToken")
	}

	var r0 entity.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.RefreshToken, error)); ok {
		return rf(token, clientID)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.RefreshToken); ok {
		r0 = rf(token, clientID)
	} else {
		r0 = ret.Get(0).(entity.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(token, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_ExchangeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeRefreshToken'
type MockIOAuth2Service_ExchangeRefreshToken_Call struct {
	*mock.Call
}

// ExchangeRefreshToken is a helper method to define mock.On call
//   - token string
//   - clientID string
func (_e *MockIOAuth2Service_Expecter) ExchangeRefreshToken(token interface{}, clientID interface{}) *MockIOAuth2Service_ExchangeRefreshToken_Call {
	return &MockIOAuth2Service_ExchangeRefreshToken_Call{Call: _e.mock.On("ExchangeRefreshToken", token, clientID)}
}

func (_c *MockIOAuth2Service_ExchangeRefreshToken_Call) Run(run func(token string, clientID string)) *MockIOAuth2Service_ExchangeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_ExchangeRefreshToken_Call) Return(_a0 entity.RefreshToken, _a1 error) *MockIOAuth2Service_ExchangeRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_ExchangeRefreshToken_Call) RunAndReturn(run func(string, string) (entity.RefreshToken, error)) *MockIOAuth2Service_ExchangeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function with given fields: id
func (_m *MockIOAuth2Service) GetClient(id string) (entity.OAuthClient, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 entity.OAuthClient
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entity.OAuthClient, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entity.OAuthClient); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.OAuthClient)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockIOAuth2Service_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - id string
func (_e *MockIOAuth2Service_Expecter) GetClient(id interface{}) *MockIOAuth2Service_GetClient_Call {
	return &MockIOAuth2Service_GetClient_Call{Call: _e.mock.On("GetClient", id)}
}

func (_c *MockIOAuth2Service_GetClient_Call) Run(run func(id string)) *MockIOAuth2Service_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_GetClient_Call) Return(_a0 entity.OAuthClient, _a1 error) *MockIOAuth2Service_GetClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_GetClient_Call) RunAndReturn(run func(string) (entity.OAuthClient, error)) *MockIOAuth2Service_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: userID
func (_m *MockIOAuth2Service) GetUserByID(userID string) (modelsentity.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 modelsentity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (modelsentity.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) modelsentity.User); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(modelsentity.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockIOAuth2Service_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - userID string
func (_e *MockIOAuth2Service_Expecter) GetUserByID(userID interface{}) *MockIOAuth2Service_GetUserByID_Call {
	return &MockIOAuth2Service_GetUserByID_Call{Call: _e.mock.On("GetUserByID", userID)}
}

func (_c *MockIOAuth2Service_GetUserByID_Call) Run(run func(userID string)) *MockIOAuth2Service_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_GetUserByID_Call) Return(_a0 modelsentity.User, _a1 error) *MockIOAuth2Service_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_GetUserByID_Call) RunAndReturn(run func(string) (modelsentity.User, error)) *MockIOAuth2Service_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// IssueAccessToken provides a mock function with given fields: clientID, userID, scope, role
func (_m *MockIOAuth2Service) IssueAccessToken(clientID string, userID string, scope string, role modelsentity.Role) (string, error) {
	ret := _m.Called(clientID, userID, scope, role)

	if len(ret) == 0 {
		panic("no return value specified for IssueAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, modelsentity.Role) (string, error)); ok {
		return rf(clientID, userID, scope, role)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, modelsentity.Role) string); ok {
		r0 = rf(clientID, userID, scope, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, modelsentity.Role) error); ok {
		r1 = rf(clientID, userID, scope, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_IssueAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueAccessToken'
type MockIOAuth2Service_IssueAccessToken_Call struct {
	*mock.Call
}

// IssueAccessToken is a helper method to define mock.On call
//   - clientID string
//   - userID string
//   - scope string
//   - role modelsentity.Role
func (_e *MockIOAuth2Service_Expecter) IssueAccessToken(clientID interface{}, userID interface{}, scope interface{}, role interface{}) *MockIOAuth2Service_IssueAccessToken_Call {
	return &MockIOAuth2Service_IssueAccessToken_Call{Call: _e.mock.On("IssueAccessToken", clientID, userID, scope, role)}
}

func (_c *MockIOAuth2Service_IssueAccessToken_Call) Run(run func(clientID string, userID string, scope string, role modelsentity.Role)) *MockIOAuth2Service_IssueAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(modelsentity.Role))
	})
	return _c
}

func (_c *MockIOAuth2Service_IssueAccessToken_Call) Return(_a0 string, _a1 error) *MockIOAuth2Service_IssueAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_IssueAccessToken_Call) RunAndReturn(run func(string, string, string, modelsentity.Role) (string, error)) *MockIOAuth2Service_IssueAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// IssueAuthCode provides a mock function with given fields: clientID, userID, redirectURI, scope
func (_m *MockIOAuth2Service) IssueAuthCode(clientID string, userID string, redirectURI string, scope string) (string, error) {
	ret := _m.Called(clientID, userID, redirectURI, scope)

	if len(ret) == 0 {
		panic("no return value specified for IssueAuthCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (string, error)); ok {
		return rf(clientID, userID, redirectURI, scope)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = rf(clientID, userID, redirectURI, scope)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(clientID, userID, redirectURI, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_IssueAuthCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueAuthCode'
type MockIOAuth2Service_IssueAuthCode_Call struct {
	*mock.Call
}

// IssueAuthCode is a helper method to define mock.On call
//   - clientID string
//   - userID string
//   - redirectURI string
//   - scope string
func (_e *MockIOAuth2Service_Expecter) IssueAuthCode(clientID interface{}, userID interface{}, redirectURI interface{}, scope interface{}) *MockIOAuth2Service_IssueAuthCode_Call {
	return &MockIOAuth2Service_IssueAuthCode_Call{Call: _e.mock.On("IssueAuthCode", clientID, userID, redirectURI, scope)}
}

func (_c *MockIOAuth2Service_IssueAuthCode_Call) Run(run func(clientID string, userID string, redirectURI string, scope string)) *MockIOAuth2Service_IssueAuthCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_IssueAuthCode_Call) Return(_a0 string, _a1 error) *MockIOAuth2Service_IssueAuthCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_IssueAuthCode_Call) RunAndReturn(run func(string, string, string, string) (string, error)) *MockIOAuth2Service_IssueAuthCode_Call {
	_c.Call.Return(run)
	return _c
}

// IssueRefreshToken provides a mock function with given fields: clientID, userID, scope
func (_m *MockIOAuth2Service) IssueRefreshToken(clientID string, userID string, scope string) (string, error) {
	ret := _m.Called(clientID, userID, scope)

	if len(ret) == 0 {
		panic("no return value specified for IssueRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(clientID, userID, scope)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(clientID, userID, scope)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(clientID, userID, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_IssueRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueRefreshToken'
type MockIOAuth2Service_IssueRefreshToken_Call struct {
	*mock.Call
}

// IssueRefreshToken is a helper method to define mock.On call
//   - clientID string
//   - userID string
//   - scope string
func (_e *MockIOAuth2Service_Expecter) IssueRefreshToken(clientID interface{}, userID interface{}, scope interface{}) *MockIOAuth2Service_IssueRefreshToken_Call {
	return &MockIOAuth2Service_IssueRefreshToken_Call{Call: _e.mock.On("IssueRefreshToken", clientID, userID, scope)}
}

func (_c *MockIOAuth2Service_IssueRefreshToken_Call) Run(run func(clientID string, userID string, scope string)) *MockIOAuth2Service_IssueRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_IssueRefreshToken_Call) Return(_a0 string, _a1 error) *MockIOAuth2Service_IssueRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_IssueRefreshToken_Call) RunAndReturn(run func(string, string, string) (string, error)) *MockIOAuth2Service_IssueRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListClients provides a mock function with given fields: ownerID
func (_m *MockIOAuth2Service) ListClients(ownerID string) ([]entity.OAuthClient, error) {
	ret := _m.Called(ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListClients")
	}

	var r0 []entity.OAuthClient
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.OAuthClient, error)); ok {
		return rf(ownerID)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.OAuthClient); ok {
		r0 = rf(ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OAuthClient)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_ListClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClients'
type MockIOAuth2Service_ListClients_Call struct {
	*mock.Call
}

// ListClients is a helper method to define mock.On call
//   - ownerID string
func (_e *MockIOAuth2Service_Expecter) ListClients(ownerID interface{}) *MockIOAuth2Service_ListClients_Call {
	return &MockIOAuth2Service_ListClients_Call{Call: _e.mock.On("ListClients", ownerID)}
}

func (_c *MockIOAuth2Service_ListClients_Call) Run(run func(ownerID string)) *MockIOAuth2Service_ListClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_ListClients_Call) Return(_a0 []entity.OAuthClient, _a1 error) *MockIOAuth2Service_ListClients_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_ListClients_Call) RunAndReturn(run func(string) ([]entity.OAuthClient, error)) *MockIOAuth2Service_ListClients_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterClient provides a mock function with given fields: ownerID, name, redirectURIs, scopes
func (_m *MockIOAuth2Service) RegisterClient(ownerID string, name string, redirectURIs []string, scopes []string) (services.ClientWithSecret, error) {
	ret := _m.Called(ownerID, name, redirectURIs, scopes)

	if len(ret) == 0 {
		panic("no return value specified for RegisterClient")
	}

	var r0 services.ClientWithSecret
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, []string, []string) (services.ClientWithSecret, error)); ok {
		return rf(ownerID, name, redirectURIs, scopes)
	}
	if rf, ok := ret.Get(0).(func(string, string, []string, []string) services.ClientWithSecret); ok {
		r0 = rf(ownerID, name, redirectURIs, scopes)
	} else {
		r0 = ret.Get(0).(services.ClientWithSecret)
	}

	if rf, ok := ret.Get(1).(func(string, string, []string, []string) error); ok {
		r1 = rf(ownerID, name, redirectURIs, scopes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_RegisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClient'
type MockIOAuth2Service_RegisterClient_Call struct {
	*mock.Call
}

// RegisterClient is a helper method to define mock.On call
//   - ownerID string
//   - name string
//   - redirectURIs []string
//   - scopes []string
func (_e *MockIOAuth2Service_Expecter) RegisterClient(ownerID interface{}, name interface{}, redirectURIs interface{}, scopes interface{}) *MockIOAuth2Service_RegisterClient_Call {
	return &MockIOAuth2Service_RegisterClient_Call{Call: _e.mock.On("RegisterClient", ownerID, name, redirectURIs, scopes)}
}

func (_c *MockIOAuth2Service_RegisterClient_Call) Run(run func(ownerID string, name string, redirectURIs []string, scopes []string)) *MockIOAuth2Service_RegisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]string), args[3].([]string))
	})
	return _c
}

func (_c *MockIOAuth2Service_RegisterClient_Call) Return(_a0 services.ClientWithSecret, _a1 error) *MockIOAuth2Service_RegisterClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_RegisterClient_Call) RunAndReturn(run func(string, string, []string, []string) (services.ClientWithSecret, error)) *MockIOAuth2Service_RegisterClient_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: token, clientID
func (_m *MockIOAuth2Service) RevokeRefreshToken(token string, clientID string) error {
	ret := _m.Called(token, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(token, clientID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOAuth2Service_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockIOAuth2Service_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - token string
//   - clientID string
func (_e *MockIOAuth2Service_Expecter) RevokeRefreshToken(token interface{}, clientID interface{}) *MockIOAuth2Service_RevokeRefreshToken_Call {
	return &MockIOAuth2Service_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", token, clientID)}
}

func (_c *MockIOAuth2Service_RevokeRefreshToken_Call) Run(run func(token string, clientID string)) *MockIOAuth2Service_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_RevokeRefreshToken_Call) Return(_a0 error) *MockIOAuth2Service_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOAuth2Service_RevokeRefreshToken_Call) RunAndReturn(run func(string, string) error) *MockIOAuth2Service_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateClient provides a mock function with given fields: clientID, clientSecret
func (_m *MockIOAuth2Service) ValidateClient(clientID string, clientSecret string) (entity.OAuthClient, error) {
	ret := _m.Called(clientID, clientSecret)

	if len(ret) == 0 {
		panic("no return value specified for ValidateClient")
	}

	var r0 entity.OAuthClient
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.OAuthClient, error)); ok {
		return rf(clientID, clientSecret)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.OAuthClient); ok {
		r0 = rf(clientID, clientSecret)
	} else {
		r0 = ret.Get(0).(entity.OAuthClient)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clientID, clientSecret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_ValidateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateClient'
type MockIOAuth2Service_ValidateClient_Call struct {
	*mock.Call
}

// ValidateClient is a helper method to define mock.On call
//   - clientID string
//   - clientSecret string
func (_e *MockIOAuth2Service_Expecter) ValidateClient(clientID interface{}, clientSecret interface{}) *MockIOAuth2Service_ValidateClient_Call {
	return &MockIOAuth2Service_ValidateClient_Call{Call: _e.mock.On("ValidateClient", clientID, clientSecret)}
}

func (_c *MockIOAuth2Service_ValidateClient_Call) Run(run func(clientID string, clientSecret string)) *MockIOAuth2Service_ValidateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_ValidateClient_Call) Return(_a0 entity.OAuthClient, _a1 error) *MockIOAuth2Service_ValidateClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_ValidateClient_Call) RunAndReturn(run func(string, string) (entity.OAuthClient, error)) *MockIOAuth2Service_ValidateClient_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: token
func (_m *MockIOAuth2Service) ValidateToken(token string) (*services.OAuth2Claims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *services.OAuth2Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*services.OAuth2Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *services.OAuth2Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.OAuth2Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockIOAuth2Service_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - token string
func (_e *MockIOAuth2Service_Expecter) ValidateToken(token interface{}) *MockIOAuth2Service_ValidateToken_Call {
	return &MockIOAuth2Service_ValidateToken_Call{Call: _e.mock.On("ValidateToken", token)}
}

func (_c *MockIOAuth2Service_ValidateToken_Call) Run(run func(token string)) *MockIOAuth2Service_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_ValidateToken_Call) Return(_a0 *services.OAuth2Claims, _a1 error) *MockIOAuth2Service_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_ValidateToken_Call) RunAndReturn(run func(string) (*services.OAuth2Claims, error)) *MockIOAuth2Service_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUserCredentials provides a mock function with given fields: email, password
func (_m *MockIOAuth2Service) ValidateUserCredentials(email string, password string) (modelsentity.User, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUserCredentials")
	}

	var r0 modelsentity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (modelsentity.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) modelsentity.User); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(modelsentity.User)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Service_ValidateUserCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUserCredentials'
type MockIOAuth2Service_ValidateUserCredentials_Call struct {
	*mock.Call
}

// ValidateUserCredentials is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *MockIOAuth2Service_Expecter) ValidateUserCredentials(email interface{}, password interface{}) *MockIOAuth2Service_ValidateUserCredentials_Call {
	return &MockIOAuth2Service_ValidateUserCredentials_Call{Call: _e.mock.On("ValidateUserCredentials", email, password)}
}

func (_c *MockIOAuth2Service_ValidateUserCredentials_Call) Run(run func(email string, password string)) *MockIOAuth2Service_ValidateUserCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIOAuth2Service_ValidateUserCredentials_Call) Return(_a0 modelsentity.User, _a1 error) *MockIOAuth2Service_ValidateUserCredentials_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Service_ValidateUserCredentials_Call) RunAndReturn(run func(string, string) (modelsentity.User, error)) *MockIOAuth2Service_ValidateUserCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOAuth2Service creates a new instance of MockIOAuth2Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOAuth2Service(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOAuth2Service {
	mock := &MockIOAuth2Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
