// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/payment/models/entity"

	mock "github.com/stretchr/testify/mock"

	modelsentity "payment-sandbox/app/modules/invoice/models/entity"
)

// MockIPaymentRepository is an autogenerated mock type for the IPaymentRepository type
type MockIPaymentRepository struct {
	mock.Mock
}

type MockIPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPaymentRepository) EXPECT() *MockIPaymentRepository_Expecter {
	return &MockIPaymentRepository_Expecter{mock: &_m.Mock}
}

// CreatePaymentIntent provides a mock function with given fields: invoiceToken, method
func (_m *MockIPaymentRepository) CreatePaymentIntent(invoiceToken string, method entity.PaymentMethod) (entity.PaymentIntent, modelsentity.Invoice, error) {
	ret := _m.Called(invoiceToken, method)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentIntent")
	}

	var r0 entity.PaymentIntent
	var r1 modelsentity.Invoice
	var r2 error
	if rf, ok := ret.Get(0).(func(string, entity.PaymentMethod) (entity.PaymentIntent, modelsentity.Invoice, error)); ok {
		return rf(invoiceToken, method)
	}
	if rf, ok := ret.Get(0).(func(string, entity.PaymentMethod) entity.PaymentIntent); ok {
		r0 = rf(invoiceToken, method)
	} else {
		r0 = ret.Get(0).(entity.PaymentIntent)
	}

	if rf, ok := ret.Get(1).(func(string, entity.PaymentMethod) modelsentity.Invoice); ok {
		r1 = rf(invoiceToken, method)
	} else {
		r1 = ret.Get(1).(modelsentity.Invoice)
	}

	if rf, ok := ret.Get(2).(func(string, entity.PaymentMethod) error); ok {
		r2 = rf(invoiceToken, method)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIPaymentRepository_CreatePaymentIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentIntent'
type MockIPaymentRepository_CreatePaymentIntent_Call struct {
	*mock.Call
}

// CreatePaymentIntent is a helper method to define mock.On call
//   - invoiceToken string
//   - method entity.PaymentMethod
func (_e *MockIPaymentRepository_Expecter) CreatePaymentIntent(invoiceToken interface{}, method interface{}) *MockIPaymentRepository_CreatePaymentIntent_Call {
	return &MockIPaymentRepository_CreatePaymentIntent_Call{Call: _e.mock.On("CreatePaymentIntent", invoiceToken, method)}
}

func (_c *MockIPaymentRepository_CreatePaymentIntent_Call) Run(run func(invoiceToken string, method entity.PaymentMethod)) *MockIPaymentRepository_CreatePaymentIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(entity.PaymentMethod))
	})
	return _c
}

func (_c *MockIPaymentRepository_CreatePaymentIntent_Call) Return(_a0 entity.PaymentIntent, _a1 modelsentity.Invoice, _a2 error) *MockIPaymentRepository_CreatePaymentIntent_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIPaymentRepository_CreatePaymentIntent_Call) RunAndReturn(run func(string, entity.PaymentMethod) (entity.PaymentIntent, modelsentity.Invoice, error)) *MockIPaymentRepository_CreatePaymentIntent_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvoiceByID provides a mock function with given fields: id
func (_m *MockIPaymentRepository) GetInvoiceByID(id string) (modelsentity.Invoice, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetInvoiceByID")
	}

	var r0 modelsentity.Invoice
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (modelsentity.Invoice, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) modelsentity.Invoice); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(modelsentity.Invoice)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIPaymentRepository_GetInvoiceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvoiceByID'
type MockIPaymentRepository_GetInvoiceByID_Call struct {
	*mock.Call
}

// GetInvoiceByID is a helper method to define mock.On call
//   - id string
func (_e *MockIPaymentRepository_Expecter) GetInvoiceByID(id interface{}) *MockIPaymentRepository_GetInvoiceByID_Call {
	return &MockIPaymentRepository_GetInvoiceByID_Call{Call: _e.mock.On("GetInvoiceByID", id)}
}

func (_c *MockIPaymentRepository_GetInvoiceByID_Call) Run(run func(id string)) *MockIPaymentRepository_GetInvoiceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPaymentRepository_GetInvoiceByID_Call) Return(_a0 modelsentity.Invoice, _a1 bool) *MockIPaymentRepository_GetInvoiceByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPaymentRepository_GetInvoiceByID_Call) RunAndReturn(run func(string) (modelsentity.Invoice, bool)) *MockIPaymentRepository_GetInvoiceByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvoiceByToken provides a mock function with given fields: token
func (_m *MockIPaymentRepository) GetInvoiceByToken(token string) (modelsentity.Invoice, bool) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetInvoiceByToken")
	}

	var r0 modelsentity.Invoice
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (modelsentity.Invoice, bool)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) modelsentity.Invoice); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(modelsentity.Invoice)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIPaymentRepository_GetInvoiceByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvoiceByToken'
type MockIPaymentRepository_GetInvoiceByToken_Call struct {
	*mock.Call
}

// GetInvoiceByToken is a helper method to define mock.On call
//   - token string
func (_e *MockIPaymentRepository_Expecter) GetInvoiceByToken(token interface{}) *MockIPaymentRepository_GetInvoiceByToken_Call {
	return &MockIPaymentRepository_GetInvoiceByToken_Call{Call: _e.mock.On("GetInvoiceByToken", token)}
}

func (_c *MockIPaymentRepository_GetInvoiceByToken_Call) Run(run func(token string)) *MockIPaymentRepository_GetInvoiceByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPaymentRepository_GetInvoiceByToken_Call) Return(_a0 modelsentity.Invoice, _a1 bool) *MockIPaymentRepository_GetInvoiceByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPaymentRepository_GetInvoiceByToken_Call) RunAndReturn(run func(string) (modelsentity.Invoice, bool)) *MockIPaymentRepository_GetInvoiceByToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaymentIntents provides a mock function with given fields: status
func (_m *MockIPaymentRepository) ListPaymentIntents(status string) []entity.PaymentIntent {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for ListPaymentIntents")
	}

	var r0 []entity.PaymentIntent
	if rf, ok := ret.Get(0).(func(string) []entity.PaymentIntent); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PaymentIntent)
		}
	}

	return r0
}

// MockIPaymentRepository_ListPaymentIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaymentIntents'
type MockIPaymentRepository_ListPaymentIntents_Call struct {
	*mock.Call
}

// ListPaymentIntents is a helper method to define mock.On call
//   - status string
func (_e *MockIPaymentRepository_Expecter) ListPaymentIntents(status interface{}) *MockIPaymentRepository_ListPaymentIntents_Call {
	return &MockIPaymentRepository_ListPaymentIntents_Call{Call: _e.mock.On("ListPaymentIntents", status)}
}

func (_c *MockIPaymentRepository_ListPaymentIntents_Call) Run(run func(status string)) *MockIPaymentRepository_ListPaymentIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPaymentRepository_ListPaymentIntents_Call) Return(_a0 []entity.PaymentIntent) *MockIPaymentRepository_ListPaymentIntents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPaymentRepository_ListPaymentIntents_Call) RunAndReturn(run func(string) []entity.PaymentIntent) *MockIPaymentRepository_ListPaymentIntents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentStatus provides a mock function with given fields: paymentID, nextStatus
func (_m *MockIPaymentRepository) UpdatePaymentStatus(paymentID string, nextStatus entity.PaymentStatus) (entity.PaymentIntent, modelsentity.Invoice, error) {
	ret := _m.Called(paymentID, nextStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 entity.PaymentIntent
	var r1 modelsentity.Invoice
	var r2 error
	if rf, ok := ret.Get(0).(func(string, entity.PaymentStatus) (entity.PaymentIntent, modelsentity.Invoice, error)); ok {
		return rf(paymentID, nextStatus)
	}
	if rf, ok := ret.Get(0).(func(string, entity.PaymentStatus) entity.PaymentIntent); ok {
		r0 = rf(paymentID, nextStatus)
	} else {
		r0 = ret.Get(0).(entity.PaymentIntent)
	}

	if rf, ok := ret.Get(1).(func(string, entity.PaymentStatus) modelsentity.Invoice); ok {
		r1 = rf(paymentID, nextStatus)
	} else {
		r1 = ret.Get(1).(modelsentity.Invoice)
	}

	if rf, ok := ret.Get(2).(func(string, entity.PaymentStatus) error); ok {
		r2 = rf(paymentID, nextStatus)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIPaymentRepository_UpdatePaymentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentStatus'
type MockIPaymentRepository_UpdatePaymentStatus_Call struct {
	*mock.Call
}

// UpdatePaymentStatus is a helper method to define mock.On call
//   - paymentID string
//   - nextStatus entity.PaymentStatus
func (_e *MockIPaymentRepository_Expecter) UpdatePaymentStatus(paymentID interface{}, nextStatus interface{}) *MockIPaymentRepository_UpdatePaymentStatus_Call {
	return &MockIPaymentRepository_UpdatePaymentStatus_Call{Call: _e.mock.On("UpdatePaymentStatus", paymentID, nextStatus)}
}

func (_c *MockIPaymentRepository_UpdatePaymentStatus_Call) Run(run func(paymentID string, nextStatus entity.PaymentStatus)) *MockIPaymentRepository_UpdatePaymentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(entity.PaymentStatus))
	})
	return _c
}

func (_c *MockIPaymentRepository_UpdatePaymentStatus_Call) Return(_a0 entity.PaymentIntent, _a1 modelsentity.Invoice, _a2 error) *MockIPaymentRepository_UpdatePaymentStatus_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIPaymentRepository_UpdatePaymentStatus_Call) RunAndReturn(run func(string, entity.PaymentStatus) (entity.PaymentIntent, modelsentity.Invoice, error)) *MockIPaymentRepository_UpdatePaymentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPaymentRepository creates a new instance of MockIPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPaymentRepository {
	mock := &MockIPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
