// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	entity0 "payment-sandbox/app/modules/invoice/models/entity"
	"payment-sandbox/app/modules/payment/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIPaymentRepository creates a new instance of MockIPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPaymentRepository {
	mock := &MockIPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPaymentRepository is an autogenerated mock type for the IPaymentRepository type
type MockIPaymentRepository struct {
	mock.Mock
}

type MockIPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPaymentRepository) EXPECT() *MockIPaymentRepository_Expecter {
	return &MockIPaymentRepository_Expecter{mock: &_m.Mock}
}

// CreatePaymentIntent provides a mock function for the type MockIPaymentRepository
func (_mock *MockIPaymentRepository) CreatePaymentIntent(invoiceToken string, method entity.PaymentMethod) (entity.PaymentIntent, entity0.Invoice, error) {
	ret := _mock.Called(invoiceToken, method)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentIntent")
	}

	var r0 entity.PaymentIntent
	var r1 entity0.Invoice
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, entity.PaymentMethod) (entity.PaymentIntent, entity0.Invoice, error)); ok {
		return returnFunc(invoiceToken, method)
	}
	if returnFunc, ok := ret.Get(0).(func(string, entity.PaymentMethod) entity.PaymentIntent); ok {
		r0 = returnFunc(invoiceToken, method)
	} else {
		r0 = ret.Get(0).(entity.PaymentIntent)
	}
	if returnFunc, ok := ret.Get(1).(func(string, entity.PaymentMethod) entity0.Invoice); ok {
		r1 = returnFunc(invoiceToken, method)
	} else {
		r1 = ret.Get(1).(entity0.Invoice)
	}
	if returnFunc, ok := ret.Get(2).(func(string, entity.PaymentMethod) error); ok {
		r2 = returnFunc(invoiceToken, method)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIPaymentRepository_CreatePaymentIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentIntent'
type MockIPaymentRepository_CreatePaymentIntent_Call struct {
	*mock.Call
}

// CreatePaymentIntent is a helper method to define mock.On call
//   - invoiceToken string
//   - method entity.PaymentMethod
func (_e *MockIPaymentRepository_Expecter) CreatePaymentIntent(invoiceToken interface{}, method interface{}) *MockIPaymentRepository_CreatePaymentIntent_Call {
	return &MockIPaymentRepository_CreatePaymentIntent_Call{Call: _e.mock.On("CreatePaymentIntent", invoiceToken, method)}
}

func (_c *MockIPaymentRepository_CreatePaymentIntent_Call) Run(run func(invoiceToken string, method entity.PaymentMethod)) *MockIPaymentRepository_CreatePaymentIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 entity.PaymentMethod
		if args[1] != nil {
			arg1 = args[1].(entity.PaymentMethod)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPaymentRepository_CreatePaymentIntent_Call) Return(paymentIntent entity.PaymentIntent, invoice entity0.Invoice, err error) *MockIPaymentRepository_CreatePaymentIntent_Call {
	_c.Call.Return(paymentIntent, invoice, err)
	return _c
}

func (_c *MockIPaymentRepository_CreatePaymentIntent_Call) RunAndReturn(run func(invoiceToken string, method entity.PaymentMethod) (entity.PaymentIntent, entity0.Invoice, error)) *MockIPaymentRepository_CreatePaymentIntent_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvoiceByToken provides a mock function for the type MockIPaymentRepository
func (_mock *MockIPaymentRepository) GetInvoiceByToken(token string) (entity0.Invoice, bool) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetInvoiceByToken")
	}

	var r0 entity0.Invoice
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (entity0.Invoice, bool)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) entity0.Invoice); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(entity0.Invoice)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockIPaymentRepository_GetInvoiceByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvoiceByToken'
type MockIPaymentRepository_GetInvoiceByToken_Call struct {
	*mock.Call
}

// GetInvoiceByToken is a helper method to define mock.On call
//   - token string
func (_e *MockIPaymentRepository_Expecter) GetInvoiceByToken(token interface{}) *MockIPaymentRepository_GetInvoiceByToken_Call {
	return &MockIPaymentRepository_GetInvoiceByToken_Call{Call: _e.mock.On("GetInvoiceByToken", token)}
}

func (_c *MockIPaymentRepository_GetInvoiceByToken_Call) Run(run func(token string)) *MockIPaymentRepository_GetInvoiceByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPaymentRepository_GetInvoiceByToken_Call) Return(invoice entity0.Invoice, b bool) *MockIPaymentRepository_GetInvoiceByToken_Call {
	_c.Call.Return(invoice, b)
	return _c
}

func (_c *MockIPaymentRepository_GetInvoiceByToken_Call) RunAndReturn(run func(token string) (entity0.Invoice, bool)) *MockIPaymentRepository_GetInvoiceByToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaymentIntents provides a mock function for the type MockIPaymentRepository
func (_mock *MockIPaymentRepository) ListPaymentIntents(status string) []entity.PaymentIntent {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for ListPaymentIntents")
	}

	var r0 []entity.PaymentIntent
	if returnFunc, ok := ret.Get(0).(func(string) []entity.PaymentIntent); ok {
		r0 = returnFunc(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PaymentIntent)
		}
	}
	return r0
}

// MockIPaymentRepository_ListPaymentIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaymentIntents'
type MockIPaymentRepository_ListPaymentIntents_Call struct {
	*mock.Call
}

// ListPaymentIntents is a helper method to define mock.On call
//   - status string
func (_e *MockIPaymentRepository_Expecter) ListPaymentIntents(status interface{}) *MockIPaymentRepository_ListPaymentIntents_Call {
	return &MockIPaymentRepository_ListPaymentIntents_Call{Call: _e.mock.On("ListPaymentIntents", status)}
}

func (_c *MockIPaymentRepository_ListPaymentIntents_Call) Run(run func(status string)) *MockIPaymentRepository_ListPaymentIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPaymentRepository_ListPaymentIntents_Call) Return(paymentIntents []entity.PaymentIntent) *MockIPaymentRepository_ListPaymentIntents_Call {
	_c.Call.Return(paymentIntents)
	return _c
}

func (_c *MockIPaymentRepository_ListPaymentIntents_Call) RunAndReturn(run func(status string) []entity.PaymentIntent) *MockIPaymentRepository_ListPaymentIntents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentStatus provides a mock function for the type MockIPaymentRepository
func (_mock *MockIPaymentRepository) UpdatePaymentStatus(paymentID string, nextStatus entity.PaymentStatus) (entity.PaymentIntent, entity0.Invoice, error) {
	ret := _mock.Called(paymentID, nextStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 entity.PaymentIntent
	var r1 entity0.Invoice
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, entity.PaymentStatus) (entity.PaymentIntent, entity0.Invoice, error)); ok {
		return returnFunc(paymentID, nextStatus)
	}
	if returnFunc, ok := ret.Get(0).(func(string, entity.PaymentStatus) entity.PaymentIntent); ok {
		r0 = returnFunc(paymentID, nextStatus)
	} else {
		r0 = ret.Get(0).(entity.PaymentIntent)
	}
	if returnFunc, ok := ret.Get(1).(func(string, entity.PaymentStatus) entity0.Invoice); ok {
		r1 = returnFunc(paymentID, nextStatus)
	} else {
		r1 = ret.Get(1).(entity0.Invoice)
	}
	if returnFunc, ok := ret.Get(2).(func(string, entity.PaymentStatus) error); ok {
		r2 = returnFunc(paymentID, nextStatus)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIPaymentRepository_UpdatePaymentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentStatus'
type MockIPaymentRepository_UpdatePaymentStatus_Call struct {
	*mock.Call
}

// UpdatePaymentStatus is a helper method to define mock.On call
//   - paymentID string
//   - nextStatus entity.PaymentStatus
func (_e *MockIPaymentRepository_Expecter) UpdatePaymentStatus(paymentID interface{}, nextStatus interface{}) *MockIPaymentRepository_UpdatePaymentStatus_Call {
	return &MockIPaymentRepository_UpdatePaymentStatus_Call{Call: _e.mock.On("UpdatePaymentStatus", paymentID, nextStatus)}
}

func (_c *MockIPaymentRepository_UpdatePaymentStatus_Call) Run(run func(paymentID string, nextStatus entity.PaymentStatus)) *MockIPaymentRepository_UpdatePaymentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 entity.PaymentStatus
		if args[1] != nil {
			arg1 = args[1].(entity.PaymentStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPaymentRepository_UpdatePaymentStatus_Call) Return(paymentIntent entity.PaymentIntent, invoice entity0.Invoice, err error) *MockIPaymentRepository_UpdatePaymentStatus_Call {
	_c.Call.Return(paymentIntent, invoice, err)
	return _c
}

func (_c *MockIPaymentRepository_UpdatePaymentStatus_Call) RunAndReturn(run func(paymentID string, nextStatus entity.PaymentStatus) (entity.PaymentIntent, entity0.Invoice, error)) *MockIPaymentRepository_UpdatePaymentStatus_Call {
	_c.Call.Return(run)
	return _c
}
