// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "payment-sandbox/app/modules/ledger/models/entity"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	uuid "github.com/google/uuid"
)

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// GetAccountByMerchantID provides a mock function with given fields: ctx, merchantID
func (_m *MockIRepository) GetAccountByMerchantID(ctx context.Context, merchantID uuid.UUID) (entity.Account, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByMerchantID")
	}

	var r0 entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entity.Account, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) entity.Account); ok {
		r0 = rf(ctx, merchantID)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_GetAccountByMerchantID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByMerchantID'
type MockIRepository_GetAccountByMerchantID_Call struct {
	*mock.Call
}

// GetAccountByMerchantID is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
func (_e *MockIRepository_Expecter) GetAccountByMerchantID(ctx interface{}, merchantID interface{}) *MockIRepository_GetAccountByMerchantID_Call {
	return &MockIRepository_GetAccountByMerchantID_Call{Call: _e.mock.On("GetAccountByMerchantID", ctx, merchantID)}
}

func (_c *MockIRepository_GetAccountByMerchantID_Call) Run(run func(ctx context.Context, merchantID uuid.UUID)) *MockIRepository_GetAccountByMerchantID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRepository_GetAccountByMerchantID_Call) Return(_a0 entity.Account, _a1 error) *MockIRepository_GetAccountByMerchantID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_GetAccountByMerchantID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (entity.Account, error)) *MockIRepository_GetAccountByMerchantID_Call {
	_c.Call.Return(run)
	return _c
}

// ListEntriesByAccount provides a mock function with given fields: ctx, accountID, filter, page, limit
func (_m *MockIRepository) ListEntriesByAccount(ctx context.Context, accountID uuid.UUID, filter entity.EntryFilter, page int, limit int) ([]entity.EntryWithTxn, int, error) {
	ret := _m.Called(ctx, accountID, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListEntriesByAccount")
	}

	var r0 []entity.EntryWithTxn
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.EntryFilter, int, int) ([]entity.EntryWithTxn, int, error)); ok {
		return rf(ctx, accountID, filter, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.EntryFilter, int, int) []entity.EntryWithTxn); ok {
		r0 = rf(ctx, accountID, filter, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.EntryWithTxn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, entity.EntryFilter, int, int) int); ok {
		r1 = rf(ctx, accountID, filter, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, entity.EntryFilter, int, int) error); ok {
		r2 = rf(ctx, accountID, filter, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIRepository_ListEntriesByAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEntriesByAccount'
type MockIRepository_ListEntriesByAccount_Call struct {
	*mock.Call
}

// ListEntriesByAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
//   - filter entity.EntryFilter
//   - page int
//   - limit int
func (_e *MockIRepository_Expecter) ListEntriesByAccount(ctx interface{}, accountID interface{}, filter interface{}, page interface{}, limit interface{}) *MockIRepository_ListEntriesByAccount_Call {
	return &MockIRepository_ListEntriesByAccount_Call{Call: _e.mock.On("ListEntriesByAccount", ctx, accountID, filter, page, limit)}
}

func (_c *MockIRepository_ListEntriesByAccount_Call) Run(run func(ctx context.Context, accountID uuid.UUID, filter entity.EntryFilter, page int, limit int)) *MockIRepository_ListEntriesByAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.EntryFilter), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockIRepository_ListEntriesByAccount_Call) Return(_a0 []entity.EntryWithTxn, _a1 int, _a2 error) *MockIRepository_ListEntriesByAccount_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIRepository_ListEntriesByAccount_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.EntryFilter, int, int) ([]entity.EntryWithTxn, int, error)) *MockIRepository_ListEntriesByAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function with given fields: ctx, tx, p
func (_m *MockIRepository) Post(ctx context.Context, tx *sql.Tx, p entity.Posting) (uuid.UUID, error) {
	ret := _m.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, entity.Posting) (uuid.UUID, error)); ok {
		return rf(ctx, tx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, entity.Posting) uuid.UUID); ok {
		r0 = rf(ctx, tx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, entity.Posting) error); ok {
		r1 = rf(ctx, tx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockIRepository_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - p entity.Posting
func (_e *MockIRepository_Expecter) Post(ctx interface{}, tx interface{}, p interface{}) *MockIRepository_Post_Call {
	return &MockIRepository_Post_Call{Call: _e.mock.On("Post", ctx, tx, p)}
}

func (_c *MockIRepository_Post_Call) Run(run func(ctx context.Context, tx *sql.Tx, p entity.Posting)) *MockIRepository_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx), args[2].(entity.Posting))
	})
	return _c
}

func (_c *MockIRepository_Post_Call) Return(_a0 uuid.UUID, _a1 error) *MockIRepository_Post_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_Post_Call) RunAndReturn(run func(context.Context, *sql.Tx, entity.Posting) (uuid.UUID, error)) *MockIRepository_Post_Call {
	_c.Call.Return(run)
	return _c
}

// Reverse provides a mock function with given fields: ctx, tx, originalRef, reason, actor
func (_m *MockIRepository) Reverse(ctx context.Context, tx *sql.Tx, originalRef string, reason string, actor uuid.UUID) (uuid.UUID, error) {
	ret := _m.Called(ctx, tx, originalRef, reason, actor)

	if len(ret) == 0 {
		panic("no return value specified for Reverse")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, string, uuid.UUID) (uuid.UUID, error)); ok {
		return rf(ctx, tx, originalRef, reason, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, string, uuid.UUID) uuid.UUID); ok {
		r0 = rf(ctx, tx, originalRef, reason, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, string, string, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, originalRef, reason, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRepository_Reverse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reverse'
type MockIRepository_Reverse_Call struct {
	*mock.Call
}

// Reverse is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - originalRef string
//   - reason string
//   - actor uuid.UUID
func (_e *MockIRepository_Expecter) Reverse(ctx interface{}, tx interface{}, originalRef interface{}, reason interface{}, actor interface{}) *MockIRepository_Reverse_Call {
	return &MockIRepository_Reverse_Call{Call: _e.mock.On("Reverse", ctx, tx, originalRef, reason, actor)}
}

func (_c *MockIRepository_Reverse_Call) Run(run func(ctx context.Context, tx *sql.Tx, originalRef string, reason string, actor uuid.UUID)) *MockIRepository_Reverse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx), args[2].(string), args[3].(string), args[4].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRepository_Reverse_Call) Return(_a0 uuid.UUID, _a1 error) *MockIRepository_Reverse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRepository_Reverse_Call) RunAndReturn(run func(context.Context, *sql.Tx, string, string, uuid.UUID) (uuid.UUID, error)) *MockIRepository_Reverse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
