// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"payment-sandbox/app/config"
	"payment-sandbox/app/middleware"
	handlers2 "payment-sandbox/app/modules/admin/handlers"
	"payment-sandbox/app/modules/admin/repositories"
	services2 "payment-sandbox/app/modules/admin/services"
	"payment-sandbox/app/modules/auth/handlers"
	"payment-sandbox/app/modules/auth/services"
	handlers4 "payment-sandbox/app/modules/invoice/handlers"
	repositories3 "payment-sandbox/app/modules/invoice/repositories"
	services4 "payment-sandbox/app/modules/invoice/services"
	handlers7 "payment-sandbox/app/modules/oauth2/handlers"
	repositories6 "payment-sandbox/app/modules/oauth2/repositories"
	services7 "payment-sandbox/app/modules/oauth2/services"
	handlers5 "payment-sandbox/app/modules/payment/handlers"
	repositories4 "payment-sandbox/app/modules/payment/repositories"
	services5 "payment-sandbox/app/modules/payment/services"
	handlers6 "payment-sandbox/app/modules/refund/handlers"
	repositories5 "payment-sandbox/app/modules/refund/repositories"
	services6 "payment-sandbox/app/modules/refund/services"
	handlers3 "payment-sandbox/app/modules/wallet/handlers"
	repositories2 "payment-sandbox/app/modules/wallet/repositories"
	services3 "payment-sandbox/app/modules/wallet/services"
	"payment-sandbox/app/shared/database"
)

// Injectors from wire.go:

func initApp() (*App, error) {
	configConfig := config.Load()
	db, err := database.New(configConfig)
	if err != nil {
		return nil, err
	}
	authRepository, err := provideAuthRepository(db)
	if err != nil {
		return nil, err
	}
	jwtService := middleware.NewJWTService(configConfig)
	authService := services.NewAuthService(authRepository, jwtService)
	authHandler := handlers.NewAuthHandler(authService)
	adminRepository := repositories.NewAdminRepository(db)
	adminService := services2.NewAdminService(adminRepository)
	adminHandler := handlers2.NewAdminHandler(adminService)
	walletRepository := repositories2.NewWalletRepository(db)
	walletService := services3.NewWalletService(walletRepository)
	iJourneyLogger := provideJourneyLogger(configConfig)
	walletHandler := handlers3.NewWalletHandler(walletService, iJourneyLogger)
	invoiceRepository := repositories3.NewInvoiceRepository(db)
	invoiceService := services4.NewInvoiceService(invoiceRepository)
	invoiceHandler := handlers4.NewInvoiceHandler(invoiceService, iJourneyLogger)
	paymentRepository := repositories4.NewPaymentRepository(db)
	paymentService := services5.NewPaymentService(paymentRepository)
	paymentHandler := handlers5.NewPaymentHandler(paymentService, iJourneyLogger)
	refundRepository := repositories5.NewRefundRepository(db)
	refundService := services6.NewRefundService(refundRepository)
	refundHandler := handlers6.NewRefundHandler(refundService, iJourneyLogger)
	oAuth2Repository := repositories6.NewOAuth2Repository(db)
	oAuth2Service := services7.NewOAuth2Service(oAuth2Repository, configConfig)
	oAuth2Handler := handlers7.NewOAuth2Handler(oAuth2Service)
	engine := newRouter(configConfig, authHandler, adminHandler, walletHandler, invoiceHandler, paymentHandler, refundHandler, oAuth2Handler)
	app := newApp(configConfig, engine)
	return app, nil
}
