// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"payment-sandbox/app/modules/auth/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIAuthService creates a new instance of MockIAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAuthService {
	mock := &MockIAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAuthService is an autogenerated mock type for the IAuthService type
type MockIAuthService struct {
	mock.Mock
}

type MockIAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAuthService) EXPECT() *MockIAuthService_Expecter {
	return &MockIAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockIAuthService
func (_mock *MockIAuthService) Login(email string, password string) (string, entity.User, error) {
	ret := _mock.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 entity.User
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, entity.User, error)); ok {
		return returnFunc(email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(email, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) entity.User); ok {
		r1 = returnFunc(email, password)
	} else {
		r1 = ret.Get(1).(entity.User)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(email, password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *MockIAuthService_Expecter) Login(email interface{}, password interface{}) *MockIAuthService_Login_Call {
	return &MockIAuthService_Login_Call{Call: _e.mock.On("Login", email, password)}
}

func (_c *MockIAuthService_Login_Call) Run(run func(email string, password string)) *MockIAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAuthService_Login_Call) Return(s string, user entity.User, err error) *MockIAuthService_Login_Call {
	_c.Call.Return(s, user, err)
	return _c
}

func (_c *MockIAuthService_Login_Call) RunAndReturn(run func(email string, password string) (string, entity.User, error)) *MockIAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterMerchant provides a mock function for the type MockIAuthService
func (_mock *MockIAuthService) RegisterMerchant(name string, email string, password string) (entity.User, error) {
	ret := _mock.Called(name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterMerchant")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (entity.User, error)); ok {
		return returnFunc(name, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) entity.User); ok {
		r0 = returnFunc(name, email, password)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(name, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAuthService_RegisterMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterMerchant'
type MockIAuthService_RegisterMerchant_Call struct {
	*mock.Call
}

// RegisterMerchant is a helper method to define mock.On call
//   - name string
//   - email string
//   - password string
func (_e *MockIAuthService_Expecter) RegisterMerchant(name interface{}, email interface{}, password interface{}) *MockIAuthService_RegisterMerchant_Call {
	return &MockIAuthService_RegisterMerchant_Call{Call: _e.mock.On("RegisterMerchant", name, email, password)}
}

func (_c *MockIAuthService_RegisterMerchant_Call) Run(run func(name string, email string, password string)) *MockIAuthService_RegisterMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAuthService_RegisterMerchant_Call) Return(user entity.User, err error) *MockIAuthService_RegisterMerchant_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIAuthService_RegisterMerchant_Call) RunAndReturn(run func(name string, email string, password string) (entity.User, error)) *MockIAuthService_RegisterMerchant_Call {
	_c.Call.Return(run)
	return _c
}
