// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/auth/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: email, password
func (_m *MockService) Login(email string, password string) (string, entity.User, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 entity.User
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (string, entity.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) entity.User); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Get(1).(entity.User)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *MockService_Expecter) Login(email interface{}, password interface{}) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", email, password)}
}

func (_c *MockService_Login_Call) Run(run func(email string, password string)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockService_Login_Call) Return(_a0 string, _a1 entity.User, _a2 error) *MockService_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(string, string) (string, entity.User, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterMerchant provides a mock function with given fields: name, email, password
func (_m *MockService) RegisterMerchant(name string, email string, password string) (entity.User, error) {
	ret := _m.Called(name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterMerchant")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (entity.User, error)); ok {
		return rf(name, email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) entity.User); ok {
		r0 = rf(name, email, password)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(name, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_RegisterMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterMerchant'
type MockService_RegisterMerchant_Call struct {
	*mock.Call
}

// RegisterMerchant is a helper method to define mock.On call
//   - name string
//   - email string
//   - password string
func (_e *MockService_Expecter) RegisterMerchant(name interface{}, email interface{}, password interface{}) *MockService_RegisterMerchant_Call {
	return &MockService_RegisterMerchant_Call{Call: _e.mock.On("RegisterMerchant", name, email, password)}
}

func (_c *MockService_RegisterMerchant_Call) Run(run func(name string, email string, password string)) *MockService_RegisterMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_RegisterMerchant_Call) Return(_a0 entity.User, _a1 error) *MockService_RegisterMerchant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_RegisterMerchant_Call) RunAndReturn(run func(string, string, string) (entity.User, error)) *MockService_RegisterMerchant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
