// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIRunner is an autogenerated mock type for the IRunner type
type MockIRunner struct {
	mock.Mock
}

type MockIRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRunner) EXPECT() *MockIRunner_Expecter {
	return &MockIRunner_Expecter{mock: &_m.Mock}
}

// CheckLedgerIntegrity provides a mock function with given fields: ctx
func (_m *MockIRunner) CheckLedgerIntegrity(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckLedgerIntegrity")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRunner_CheckLedgerIntegrity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckLedgerIntegrity'
type MockIRunner_CheckLedgerIntegrity_Call struct {
	*mock.Call
}

// CheckLedgerIntegrity is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIRunner_Expecter) CheckLedgerIntegrity(ctx interface{}) *MockIRunner_CheckLedgerIntegrity_Call {
	return &MockIRunner_CheckLedgerIntegrity_Call{Call: _e.mock.On("CheckLedgerIntegrity", ctx)}
}

func (_c *MockIRunner_CheckLedgerIntegrity_Call) Run(run func(ctx context.Context)) *MockIRunner_CheckLedgerIntegrity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIRunner_CheckLedgerIntegrity_Call) Return(_a0 []string, _a1 error) *MockIRunner_CheckLedgerIntegrity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRunner_CheckLedgerIntegrity_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockIRunner_CheckLedgerIntegrity_Call {
	_c.Call.Return(run)
	return _c
}

// CheckTransactionBalance provides a mock function with given fields: ctx
func (_m *MockIRunner) CheckTransactionBalance(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckTransactionBalance")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRunner_CheckTransactionBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckTransactionBalance'
type MockIRunner_CheckTransactionBalance_Call struct {
	*mock.Call
}

// CheckTransactionBalance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIRunner_Expecter) CheckTransactionBalance(ctx interface{}) *MockIRunner_CheckTransactionBalance_Call {
	return &MockIRunner_CheckTransactionBalance_Call{Call: _e.mock.On("CheckTransactionBalance", ctx)}
}

func (_c *MockIRunner_CheckTransactionBalance_Call) Run(run func(ctx context.Context)) *MockIRunner_CheckTransactionBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIRunner_CheckTransactionBalance_Call) Return(_a0 []string, _a1 error) *MockIRunner_CheckTransactionBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRunner_CheckTransactionBalance_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockIRunner_CheckTransactionBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRunner creates a new instance of MockIRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRunner {
	mock := &MockIRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
