// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/oauth2/models/entity"

	mock "github.com/stretchr/testify/mock"

	modelsentity "payment-sandbox/app/modules/users/models/entity"
)

// MockIOAuth2Repository is an autogenerated mock type for the IOAuth2Repository type
type MockIOAuth2Repository struct {
	mock.Mock
}

type MockIOAuth2Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOAuth2Repository) EXPECT() *MockIOAuth2Repository_Expecter {
	return &MockIOAuth2Repository_Expecter{mock: &_m.Mock}
}

// CreateClient provides a mock function with given fields: client
func (_m *MockIOAuth2Repository) CreateClient(client entity.OAuthClient) (entity.OAuthClient, error) {
	ret := _m.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for CreateClient")
	}

	var r0 entity.OAuthClient
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.OAuthClient) (entity.OAuthClient, error)); ok {
		return rf(client)
	}
	if rf, ok := ret.Get(0).(func(entity.OAuthClient) entity.OAuthClient); ok {
		r0 = rf(client)
	} else {
		r0 = ret.Get(0).(entity.OAuthClient)
	}

	if rf, ok := ret.Get(1).(func(entity.OAuthClient) error); ok {
		r1 = rf(client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Repository_CreateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClient'
type MockIOAuth2Repository_CreateClient_Call struct {
	*mock.Call
}

// CreateClient is a helper method to define mock.On call
//   - client entity.OAuthClient
func (_e *MockIOAuth2Repository_Expecter) CreateClient(client interface{}) *MockIOAuth2Repository_CreateClient_Call {
	return &MockIOAuth2Repository_CreateClient_Call{Call: _e.mock.On("CreateClient", client)}
}

func (_c *MockIOAuth2Repository_CreateClient_Call) Run(run func(client entity.OAuthClient)) *MockIOAuth2Repository_CreateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.OAuthClient))
	})
	return _c
}

func (_c *MockIOAuth2Repository_CreateClient_Call) Return(_a0 entity.OAuthClient, _a1 error) *MockIOAuth2Repository_CreateClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Repository_CreateClient_Call) RunAndReturn(run func(entity.OAuthClient) (entity.OAuthClient, error)) *MockIOAuth2Repository_CreateClient_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClient provides a mock function with given fields: id, ownerID
func (_m *MockIOAuth2Repository) DeleteClient(id string, ownerID string) error {
	ret := _m.Called(id, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, ownerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOAuth2Repository_DeleteClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClient'
type MockIOAuth2Repository_DeleteClient_Call struct {
	*mock.Call
}

// DeleteClient is a helper method to define mock.On call
//   - id string
//   - ownerID string
func (_e *MockIOAuth2Repository_Expecter) DeleteClient(id interface{}, ownerID interface{}) *MockIOAuth2Repository_DeleteClient_Call {
	return &MockIOAuth2Repository_DeleteClient_Call{Call: _e.mock.On("DeleteClient", id, ownerID)}
}

func (_c *MockIOAuth2Repository_DeleteClient_Call) Run(run func(id string, ownerID string)) *MockIOAuth2Repository_DeleteClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIOAuth2Repository_DeleteClient_Call) Return(_a0 error) *MockIOAuth2Repository_DeleteClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOAuth2Repository_DeleteClient_Call) RunAndReturn(run func(string, string) error) *MockIOAuth2Repository_DeleteClient_Call {
	_c.Call.Return(run)
	return _c
}

// FindAuthCode provides a mock function with given fields: code
func (_m *MockIOAuth2Repository) FindAuthCode(code string) (entity.AuthorizationCode, bool) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for FindAuthCode")
	}

	var r0 entity.AuthorizationCode
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (entity.AuthorizationCode, bool)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) entity.AuthorizationCode); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(entity.AuthorizationCode)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIOAuth2Repository_FindAuthCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAuthCode'
type MockIOAuth2Repository_FindAuthCode_Call struct {
	*mock.Call
}

// FindAuthCode is a helper method to define mock.On call
//   - code string
func (_e *MockIOAuth2Repository_Expecter) FindAuthCode(code interface{}) *MockIOAuth2Repository_FindAuthCode_Call {
	return &MockIOAuth2Repository_FindAuthCode_Call{Call: _e.mock.On("FindAuthCode", code)}
}

func (_c *MockIOAuth2Repository_FindAuthCode_Call) Run(run func(code string)) *MockIOAuth2Repository_FindAuthCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Repository_FindAuthCode_Call) Return(_a0 entity.AuthorizationCode, _a1 bool) *MockIOAuth2Repository_FindAuthCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Repository_FindAuthCode_Call) RunAndReturn(run func(string) (entity.AuthorizationCode, bool)) *MockIOAuth2Repository_FindAuthCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindClientByID provides a mock function with given fields: id
func (_m *MockIOAuth2Repository) FindClientByID(id string) (entity.OAuthClient, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindClientByID")
	}

	var r0 entity.OAuthClient
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (entity.OAuthClient, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entity.OAuthClient); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.OAuthClient)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIOAuth2Repository_FindClientByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindClientByID'
type MockIOAuth2Repository_FindClientByID_Call struct {
	*mock.Call
}

// FindClientByID is a helper method to define mock.On call
//   - id string
func (_e *MockIOAuth2Repository_Expecter) FindClientByID(id interface{}) *MockIOAuth2Repository_FindClientByID_Call {
	return &MockIOAuth2Repository_FindClientByID_Call{Call: _e.mock.On("FindClientByID", id)}
}

func (_c *MockIOAuth2Repository_FindClientByID_Call) Run(run func(id string)) *MockIOAuth2Repository_FindClientByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Repository_FindClientByID_Call) Return(_a0 entity.OAuthClient, _a1 bool) *MockIOAuth2Repository_FindClientByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Repository_FindClientByID_Call) RunAndReturn(run func(string) (entity.OAuthClient, bool)) *MockIOAuth2Repository_FindClientByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindConsent provides a mock function with given fields: userID, clientID
func (_m *MockIOAuth2Repository) FindConsent(userID string, clientID string) (entity.Consent, bool) {
	ret := _m.Called(userID, clientID)

	if len(ret) == 0 {
		panic("no return value specified for FindConsent")
	}

	var r0 entity.Consent
	var r1 bool
	if rf, ok := ret.Get(0).(func(string, string) (entity.Consent, bool)); ok {
		return rf(userID, clientID)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.Consent); ok {
		r0 = rf(userID, clientID)
	} else {
		r0 = ret.Get(0).(entity.Consent)
	}

	if rf, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = rf(userID, clientID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIOAuth2Repository_FindConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindConsent'
type MockIOAuth2Repository_FindConsent_Call struct {
	*mock.Call
}

// FindConsent is a helper method to define mock.On call
//   - userID string
//   - clientID string
func (_e *MockIOAuth2Repository_Expecter) FindConsent(userID interface{}, clientID interface{}) *MockIOAuth2Repository_FindConsent_Call {
	return &MockIOAuth2Repository_FindConsent_Call{Call: _e.mock.On("FindConsent", userID, clientID)}
}

func (_c *MockIOAuth2Repository_FindConsent_Call) Run(run func(userID string, clientID string)) *MockIOAuth2Repository_FindConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIOAuth2Repository_FindConsent_Call) Return(_a0 entity.Consent, _a1 bool) *MockIOAuth2Repository_FindConsent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Repository_FindConsent_Call) RunAndReturn(run func(string, string) (entity.Consent, bool)) *MockIOAuth2Repository_FindConsent_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefreshToken provides a mock function with given fields: token
func (_m *MockIOAuth2Repository) FindRefreshToken(token string) (entity.RefreshToken, bool) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for FindRefreshToken")
	}

	var r0 entity.RefreshToken
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (entity.RefreshToken, bool)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) entity.RefreshToken); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(entity.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIOAuth2Repository_FindRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefreshToken'
type MockIOAuth2Repository_FindRefreshToken_Call struct {
	*mock.Call
}

// FindRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockIOAuth2Repository_Expecter) FindRefreshToken(token interface{}) *MockIOAuth2Repository_FindRefreshToken_Call {
	return &MockIOAuth2Repository_FindRefreshToken_Call{Call: _e.mock.On("FindRefreshToken", token)}
}

func (_c *MockIOAuth2Repository_FindRefreshToken_Call) Run(run func(token string)) *MockIOAuth2Repository_FindRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Repository_FindRefreshToken_Call) Return(_a0 entity.RefreshToken, _a1 bool) *MockIOAuth2Repository_FindRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Repository_FindRefreshToken_Call) RunAndReturn(run func(string) (entity.RefreshToken, bool)) *MockIOAuth2Repository_FindRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function with given fields: email
func (_m *MockIOAuth2Repository) FindUserByEmail(email string) (modelsentity.User, bool) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 modelsentity.User
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (modelsentity.User, bool)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) modelsentity.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(modelsentity.User)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIOAuth2Repository_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockIOAuth2Repository_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockIOAuth2Repository_Expecter) FindUserByEmail(email interface{}) *MockIOAuth2Repository_FindUserByEmail_Call {
	return &MockIOAuth2Repository_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", email)}
}

func (_c *MockIOAuth2Repository_FindUserByEmail_Call) Run(run func(email string)) *MockIOAuth2Repository_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Repository_FindUserByEmail_Call) Return(_a0 modelsentity.User, _a1 bool) *MockIOAuth2Repository_FindUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Repository_FindUserByEmail_Call) RunAndReturn(run func(string) (modelsentity.User, bool)) *MockIOAuth2Repository_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function with given fields: id
func (_m *MockIOAuth2Repository) FindUserByID(id string) (modelsentity.User, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 modelsentity.User
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (modelsentity.User, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) modelsentity.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(modelsentity.User)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIOAuth2Repository_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type MockIOAuth2Repository_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - id string
func (_e *MockIOAuth2Repository_Expecter) FindUserByID(id interface{}) *MockIOAuth2Repository_FindUserByID_Call {
	return &MockIOAuth2Repository_FindUserByID_Call{Call: _e.mock.On("FindUserByID", id)}
}

func (_c *MockIOAuth2Repository_FindUserByID_Call) Run(run func(id string)) *MockIOAuth2Repository_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Repository_FindUserByID_Call) Return(_a0 modelsentity.User, _a1 bool) *MockIOAuth2Repository_FindUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Repository_FindUserByID_Call) RunAndReturn(run func(string) (modelsentity.User, bool)) *MockIOAuth2Repository_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListClientsByOwner provides a mock function with given fields: ownerID
func (_m *MockIOAuth2Repository) ListClientsByOwner(ownerID string) ([]entity.OAuthClient, error) {
	ret := _m.Called(ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListClientsByOwner")
	}

	var r0 []entity.OAuthClient
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.OAuthClient, error)); ok {
		return rf(ownerID)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.OAuthClient); ok {
		r0 = rf(ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OAuthClient)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOAuth2Repository_ListClientsByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClientsByOwner'
type MockIOAuth2Repository_ListClientsByOwner_Call struct {
	*mock.Call
}

// ListClientsByOwner is a helper method to define mock.On call
//   - ownerID string
func (_e *MockIOAuth2Repository_Expecter) ListClientsByOwner(ownerID interface{}) *MockIOAuth2Repository_ListClientsByOwner_Call {
	return &MockIOAuth2Repository_ListClientsByOwner_Call{Call: _e.mock.On("ListClientsByOwner", ownerID)}
}

func (_c *MockIOAuth2Repository_ListClientsByOwner_Call) Run(run func(ownerID string)) *MockIOAuth2Repository_ListClientsByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Repository_ListClientsByOwner_Call) Return(_a0 []entity.OAuthClient, _a1 error) *MockIOAuth2Repository_ListClientsByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOAuth2Repository_ListClientsByOwner_Call) RunAndReturn(run func(string) ([]entity.OAuthClient, error)) *MockIOAuth2Repository_ListClientsByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAuthCodeUsed provides a mock function with given fields: code
func (_m *MockIOAuth2Repository) MarkAuthCodeUsed(code string) error {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for MarkAuthCodeUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOAuth2Repository_MarkAuthCodeUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAuthCodeUsed'
type MockIOAuth2Repository_MarkAuthCodeUsed_Call struct {
	*mock.Call
}

// MarkAuthCodeUsed is a helper method to define mock.On call
//   - code string
func (_e *MockIOAuth2Repository_Expecter) MarkAuthCodeUsed(code interface{}) *MockIOAuth2Repository_MarkAuthCodeUsed_Call {
	return &MockIOAuth2Repository_MarkAuthCodeUsed_Call{Call: _e.mock.On("MarkAuthCodeUsed", code)}
}

func (_c *MockIOAuth2Repository_MarkAuthCodeUsed_Call) Run(run func(code string)) *MockIOAuth2Repository_MarkAuthCodeUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Repository_MarkAuthCodeUsed_Call) Return(_a0 error) *MockIOAuth2Repository_MarkAuthCodeUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOAuth2Repository_MarkAuthCodeUsed_Call) RunAndReturn(run func(string) error) *MockIOAuth2Repository_MarkAuthCodeUsed_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllRefreshTokens provides a mock function with given fields: clientID, userID
func (_m *MockIOAuth2Repository) RevokeAllRefreshTokens(clientID string, userID string) error {
	ret := _m.Called(clientID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllRefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(clientID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOAuth2Repository_RevokeAllRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllRefreshTokens'
type MockIOAuth2Repository_RevokeAllRefreshTokens_Call struct {
	*mock.Call
}

// RevokeAllRefreshTokens is a helper method to define mock.On call
//   - clientID string
//   - userID string
func (_e *MockIOAuth2Repository_Expecter) RevokeAllRefreshTokens(clientID interface{}, userID interface{}) *MockIOAuth2Repository_RevokeAllRefreshTokens_Call {
	return &MockIOAuth2Repository_RevokeAllRefreshTokens_Call{Call: _e.mock.On("RevokeAllRefreshTokens", clientID, userID)}
}

func (_c *MockIOAuth2Repository_RevokeAllRefreshTokens_Call) Run(run func(clientID string, userID string)) *MockIOAuth2Repository_RevokeAllRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIOAuth2Repository_RevokeAllRefreshTokens_Call) Return(_a0 error) *MockIOAuth2Repository_RevokeAllRefreshTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOAuth2Repository_RevokeAllRefreshTokens_Call) RunAndReturn(run func(string, string) error) *MockIOAuth2Repository_RevokeAllRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: token
func (_m *MockIOAuth2Repository) RevokeRefreshToken(token string) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOAuth2Repository_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockIOAuth2Repository_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockIOAuth2Repository_Expecter) RevokeRefreshToken(token interface{}) *MockIOAuth2Repository_RevokeRefreshToken_Call {
	return &MockIOAuth2Repository_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", token)}
}

func (_c *MockIOAuth2Repository_RevokeRefreshToken_Call) Run(run func(token string)) *MockIOAuth2Repository_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIOAuth2Repository_RevokeRefreshToken_Call) Return(_a0 error) *MockIOAuth2Repository_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOAuth2Repository_RevokeRefreshToken_Call) RunAndReturn(run func(string) error) *MockIOAuth2Repository_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAuthCode provides a mock function with given fields: code
func (_m *MockIOAuth2Repository) SaveAuthCode(code entity.AuthorizationCode) error {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for SaveAuthCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.AuthorizationCode) error); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOAuth2Repository_SaveAuthCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAuthCode'
type MockIOAuth2Repository_SaveAuthCode_Call struct {
	*mock.Call
}

// SaveAuthCode is a helper method to define mock.On call
//   - code entity.AuthorizationCode
func (_e *MockIOAuth2Repository_Expecter) SaveAuthCode(code interface{}) *MockIOAuth2Repository_SaveAuthCode_Call {
	return &MockIOAuth2Repository_SaveAuthCode_Call{Call: _e.mock.On("SaveAuthCode", code)}
}

func (_c *MockIOAuth2Repository_SaveAuthCode_Call) Run(run func(code entity.AuthorizationCode)) *MockIOAuth2Repository_SaveAuthCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.AuthorizationCode))
	})
	return _c
}

func (_c *MockIOAuth2Repository_SaveAuthCode_Call) Return(_a0 error) *MockIOAuth2Repository_SaveAuthCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOAuth2Repository_SaveAuthCode_Call) RunAndReturn(run func(entity.AuthorizationCode) error) *MockIOAuth2Repository_SaveAuthCode_Call {
	_c.Call.Return(run)
	return _c
}

// SaveConsent provides a mock function with given fields: consent
func (_m *MockIOAuth2Repository) SaveConsent(consent entity.Consent) error {
	ret := _m.Called(consent)

	if len(ret) == 0 {
		panic("no return value specified for SaveConsent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Consent) error); ok {
		r0 = rf(consent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOAuth2Repository_SaveConsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveConsent'
type MockIOAuth2Repository_SaveConsent_Call struct {
	*mock.Call
}

// SaveConsent is a helper method to define mock.On call
//   - consent entity.Consent
func (_e *MockIOAuth2Repository_Expecter) SaveConsent(consent interface{}) *MockIOAuth2Repository_SaveConsent_Call {
	return &MockIOAuth2Repository_SaveConsent_Call{Call: _e.mock.On("SaveConsent", consent)}
}

func (_c *MockIOAuth2Repository_SaveConsent_Call) Run(run func(consent entity.Consent)) *MockIOAuth2Repository_SaveConsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.Consent))
	})
	return _c
}

func (_c *MockIOAuth2Repository_SaveConsent_Call) Return(_a0 error) *MockIOAuth2Repository_SaveConsent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOAuth2Repository_SaveConsent_Call) RunAndReturn(run func(entity.Consent) error) *MockIOAuth2Repository_SaveConsent_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshToken provides a mock function with given fields: token
func (_m *MockIOAuth2Repository) SaveRefreshToken(token entity.RefreshToken) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.RefreshToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOAuth2Repository_SaveRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshToken'
type MockIOAuth2Repository_SaveRefreshToken_Call struct {
	*mock.Call
}

// SaveRefreshToken is a helper method to define mock.On call
//   - token entity.RefreshToken
func (_e *MockIOAuth2Repository_Expecter) SaveRefreshToken(token interface{}) *MockIOAuth2Repository_SaveRefreshToken_Call {
	return &MockIOAuth2Repository_SaveRefreshToken_Call{Call: _e.mock.On("SaveRefreshToken", token)}
}

func (_c *MockIOAuth2Repository_SaveRefreshToken_Call) Run(run func(token entity.RefreshToken)) *MockIOAuth2Repository_SaveRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.RefreshToken))
	})
	return _c
}

func (_c *MockIOAuth2Repository_SaveRefreshToken_Call) Return(_a0 error) *MockIOAuth2Repository_SaveRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOAuth2Repository_SaveRefreshToken_Call) RunAndReturn(run func(entity.RefreshToken) error) *MockIOAuth2Repository_SaveRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOAuth2Repository creates a new instance of MockIOAuth2Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOAuth2Repository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOAuth2Repository {
	mock := &MockIOAuth2Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
