// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	audit "payment-sandbox/app/shared/audit"

	mock "github.com/stretchr/testify/mock"
)

// IAuditLogger is an autogenerated mock type for the IAuditLogger type
type IAuditLogger struct {
	mock.Mock
}

type IAuditLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *IAuditLogger) EXPECT() *IAuditLogger_Expecter {
	return &IAuditLogger_Expecter{mock: &_m.Mock}
}

// Log provides a mock function with given fields: ctx, event
func (_m *IAuditLogger) Log(ctx context.Context, event audit.Event) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, audit.Event) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IAuditLogger_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type IAuditLogger_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - ctx context.Context
//   - event audit.Event
func (_e *IAuditLogger_Expecter) Log(ctx interface{}, event interface{}) *IAuditLogger_Log_Call {
	return &IAuditLogger_Log_Call{Call: _e.mock.On("Log", ctx, event)}
}

func (_c *IAuditLogger_Log_Call) Run(run func(ctx context.Context, event audit.Event)) *IAuditLogger_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(audit.Event))
	})
	return _c
}

func (_c *IAuditLogger_Log_Call) Return(_a0 error) *IAuditLogger_Log_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAuditLogger_Log_Call) RunAndReturn(run func(context.Context, audit.Event) error) *IAuditLogger_Log_Call {
	_c.Call.Return(run)
	return _c
}

// NewIAuditLogger creates a new instance of IAuditLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuditLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuditLogger {
	mock := &IAuditLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
