// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/refund/models/entity"

	mock "github.com/stretchr/testify/mock"

	modelsentity "payment-sandbox/app/modules/wallet/models/entity"
)

// MockIRefundRepository is an autogenerated mock type for the IRefundRepository type
type MockIRefundRepository struct {
	mock.Mock
}

type MockIRefundRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRefundRepository) EXPECT() *MockIRefundRepository_Expecter {
	return &MockIRefundRepository_Expecter{mock: &_m.Mock}
}

// ListMerchantRefunds provides a mock function with given fields: merchantID, status
func (_m *MockIRefundRepository) ListMerchantRefunds(merchantID string, status string) []entity.Refund {
	ret := _m.Called(merchantID, status)

	if len(ret) == 0 {
		panic("no return value specified for ListMerchantRefunds")
	}

	var r0 []entity.Refund
	if rf, ok := ret.Get(0).(func(string, string) []entity.Refund); ok {
		r0 = rf(merchantID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Refund)
		}
	}

	return r0
}

// MockIRefundRepository_ListMerchantRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMerchantRefunds'
type MockIRefundRepository_ListMerchantRefunds_Call struct {
	*mock.Call
}

// ListMerchantRefunds is a helper method to define mock.On call
//   - merchantID string
//   - status string
func (_e *MockIRefundRepository_Expecter) ListMerchantRefunds(merchantID interface{}, status interface{}) *MockIRefundRepository_ListMerchantRefunds_Call {
	return &MockIRefundRepository_ListMerchantRefunds_Call{Call: _e.mock.On("ListMerchantRefunds", merchantID, status)}
}

func (_c *MockIRefundRepository_ListMerchantRefunds_Call) Run(run func(merchantID string, status string)) *MockIRefundRepository_ListMerchantRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIRefundRepository_ListMerchantRefunds_Call) Return(_a0 []entity.Refund) *MockIRefundRepository_ListMerchantRefunds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRefundRepository_ListMerchantRefunds_Call) RunAndReturn(run func(string, string) []entity.Refund) *MockIRefundRepository_ListMerchantRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// ListRefunds provides a mock function with given fields: status
func (_m *MockIRefundRepository) ListRefunds(status string) []entity.Refund {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for ListRefunds")
	}

	var r0 []entity.Refund
	if rf, ok := ret.Get(0).(func(string) []entity.Refund); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Refund)
		}
	}

	return r0
}

// MockIRefundRepository_ListRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRefunds'
type MockIRefundRepository_ListRefunds_Call struct {
	*mock.Call
}

// ListRefunds is a helper method to define mock.On call
//   - status string
func (_e *MockIRefundRepository_Expecter) ListRefunds(status interface{}) *MockIRefundRepository_ListRefunds_Call {
	return &MockIRefundRepository_ListRefunds_Call{Call: _e.mock.On("ListRefunds", status)}
}

func (_c *MockIRefundRepository_ListRefunds_Call) Run(run func(status string)) *MockIRefundRepository_ListRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIRefundRepository_ListRefunds_Call) Return(_a0 []entity.Refund) *MockIRefundRepository_ListRefunds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRefundRepository_ListRefunds_Call) RunAndReturn(run func(string) []entity.Refund) *MockIRefundRepository_ListRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantIDByUserID provides a mock function with given fields: userID
func (_m *MockIRefundRepository) MerchantIDByUserID(userID string) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for MerchantIDByUserID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRefundRepository_MerchantIDByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantIDByUserID'
type MockIRefundRepository_MerchantIDByUserID_Call struct {
	*mock.Call
}

// MerchantIDByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockIRefundRepository_Expecter) MerchantIDByUserID(userID interface{}) *MockIRefundRepository_MerchantIDByUserID_Call {
	return &MockIRefundRepository_MerchantIDByUserID_Call{Call: _e.mock.On("MerchantIDByUserID", userID)}
}

func (_c *MockIRefundRepository_MerchantIDByUserID_Call) Run(run func(userID string)) *MockIRefundRepository_MerchantIDByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIRefundRepository_MerchantIDByUserID_Call) Return(_a0 string, _a1 error) *MockIRefundRepository_MerchantIDByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRefundRepository_MerchantIDByUserID_Call) RunAndReturn(run func(string) (string, error)) *MockIRefundRepository_MerchantIDByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessRefund provides a mock function with given fields: refundID, nextStatus
func (_m *MockIRefundRepository) ProcessRefund(refundID string, nextStatus entity.RefundStatus) (entity.Refund, modelsentity.Merchant, error) {
	ret := _m.Called(refundID, nextStatus)

	if len(ret) == 0 {
		panic("no return value specified for ProcessRefund")
	}

	var r0 entity.Refund
	var r1 modelsentity.Merchant
	var r2 error
	if rf, ok := ret.Get(0).(func(string, entity.RefundStatus) (entity.Refund, modelsentity.Merchant, error)); ok {
		return rf(refundID, nextStatus)
	}
	if rf, ok := ret.Get(0).(func(string, entity.RefundStatus) entity.Refund); ok {
		r0 = rf(refundID, nextStatus)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, entity.RefundStatus) modelsentity.Merchant); ok {
		r1 = rf(refundID, nextStatus)
	} else {
		r1 = ret.Get(1).(modelsentity.Merchant)
	}

	if rf, ok := ret.Get(2).(func(string, entity.RefundStatus) error); ok {
		r2 = rf(refundID, nextStatus)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIRefundRepository_ProcessRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessRefund'
type MockIRefundRepository_ProcessRefund_Call struct {
	*mock.Call
}

// ProcessRefund is a helper method to define mock.On call
//   - refundID string
//   - nextStatus entity.RefundStatus
func (_e *MockIRefundRepository_Expecter) ProcessRefund(refundID interface{}, nextStatus interface{}) *MockIRefundRepository_ProcessRefund_Call {
	return &MockIRefundRepository_ProcessRefund_Call{Call: _e.mock.On("ProcessRefund", refundID, nextStatus)}
}

func (_c *MockIRefundRepository_ProcessRefund_Call) Run(run func(refundID string, nextStatus entity.RefundStatus)) *MockIRefundRepository_ProcessRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(entity.RefundStatus))
	})
	return _c
}

func (_c *MockIRefundRepository_ProcessRefund_Call) Return(_a0 entity.Refund, _a1 modelsentity.Merchant, _a2 error) *MockIRefundRepository_ProcessRefund_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIRefundRepository_ProcessRefund_Call) RunAndReturn(run func(string, entity.RefundStatus) (entity.Refund, modelsentity.Merchant, error)) *MockIRefundRepository_ProcessRefund_Call {
	_c.Call.Return(run)
	return _c
}

// RequestRefund provides a mock function with given fields: merchantID, invoiceID, reason
func (_m *MockIRefundRepository) RequestRefund(merchantID string, invoiceID string, reason string) (entity.Refund, error) {
	ret := _m.Called(merchantID, invoiceID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RequestRefund")
	}

	var r0 entity.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (entity.Refund, error)); ok {
		return rf(merchantID, invoiceID, reason)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) entity.Refund); ok {
		r0 = rf(merchantID, invoiceID, reason)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(merchantID, invoiceID, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRefundRepository_RequestRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestRefund'
type MockIRefundRepository_RequestRefund_Call struct {
	*mock.Call
}

// RequestRefund is a helper method to define mock.On call
//   - merchantID string
//   - invoiceID string
//   - reason string
func (_e *MockIRefundRepository_Expecter) RequestRefund(merchantID interface{}, invoiceID interface{}, reason interface{}) *MockIRefundRepository_RequestRefund_Call {
	return &MockIRefundRepository_RequestRefund_Call{Call: _e.mock.On("RequestRefund", merchantID, invoiceID, reason)}
}

func (_c *MockIRefundRepository_RequestRefund_Call) Run(run func(merchantID string, invoiceID string, reason string)) *MockIRefundRepository_RequestRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIRefundRepository_RequestRefund_Call) Return(_a0 entity.Refund, _a1 error) *MockIRefundRepository_RequestRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRefundRepository_RequestRefund_Call) RunAndReturn(run func(string, string, string) (entity.Refund, error)) *MockIRefundRepository_RequestRefund_Call {
	_c.Call.Return(run)
	return _c
}

// ReviewRefund provides a mock function with given fields: refundID, approved
func (_m *MockIRefundRepository) ReviewRefund(refundID string, approved bool) (entity.Refund, error) {
	ret := _m.Called(refundID, approved)

	if len(ret) == 0 {
		panic("no return value specified for ReviewRefund")
	}

	var r0 entity.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) (entity.Refund, error)); ok {
		return rf(refundID, approved)
	}
	if rf, ok := ret.Get(0).(func(string, bool) entity.Refund); ok {
		r0 = rf(refundID, approved)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(refundID, approved)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRefundRepository_ReviewRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReviewRefund'
type MockIRefundRepository_ReviewRefund_Call struct {
	*mock.Call
}

// ReviewRefund is a helper method to define mock.On call
//   - refundID string
//   - approved bool
func (_e *MockIRefundRepository_Expecter) ReviewRefund(refundID interface{}, approved interface{}) *MockIRefundRepository_ReviewRefund_Call {
	return &MockIRefundRepository_ReviewRefund_Call{Call: _e.mock.On("ReviewRefund", refundID, approved)}
}

func (_c *MockIRefundRepository_ReviewRefund_Call) Run(run func(refundID string, approved bool)) *MockIRefundRepository_ReviewRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockIRefundRepository_ReviewRefund_Call) Return(_a0 entity.Refund, _a1 error) *MockIRefundRepository_ReviewRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRefundRepository_ReviewRefund_Call) RunAndReturn(run func(string, bool) (entity.Refund, error)) *MockIRefundRepository_ReviewRefund_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRefundRepository creates a new instance of MockIRefundRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRefundRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRefundRepository {
	mock := &MockIRefundRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
