// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"payment-sandbox/app/modules/refund/models/entity"
	entity0 "payment-sandbox/app/modules/wallet/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIRefundRepository creates a new instance of MockIRefundRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRefundRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRefundRepository {
	mock := &MockIRefundRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRefundRepository is an autogenerated mock type for the IRefundRepository type
type MockIRefundRepository struct {
	mock.Mock
}

type MockIRefundRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRefundRepository) EXPECT() *MockIRefundRepository_Expecter {
	return &MockIRefundRepository_Expecter{mock: &_m.Mock}
}

// ListRefunds provides a mock function for the type MockIRefundRepository
func (_mock *MockIRefundRepository) ListRefunds(status string) []entity.Refund {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for ListRefunds")
	}

	var r0 []entity.Refund
	if returnFunc, ok := ret.Get(0).(func(string) []entity.Refund); ok {
		r0 = returnFunc(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Refund)
		}
	}
	return r0
}

// MockIRefundRepository_ListRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRefunds'
type MockIRefundRepository_ListRefunds_Call struct {
	*mock.Call
}

// ListRefunds is a helper method to define mock.On call
//   - status string
func (_e *MockIRefundRepository_Expecter) ListRefunds(status interface{}) *MockIRefundRepository_ListRefunds_Call {
	return &MockIRefundRepository_ListRefunds_Call{Call: _e.mock.On("ListRefunds", status)}
}

func (_c *MockIRefundRepository_ListRefunds_Call) Run(run func(status string)) *MockIRefundRepository_ListRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRefundRepository_ListRefunds_Call) Return(refunds []entity.Refund) *MockIRefundRepository_ListRefunds_Call {
	_c.Call.Return(refunds)
	return _c
}

func (_c *MockIRefundRepository_ListRefunds_Call) RunAndReturn(run func(status string) []entity.Refund) *MockIRefundRepository_ListRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantIDByUserID provides a mock function for the type MockIRefundRepository
func (_mock *MockIRefundRepository) MerchantIDByUserID(userID string) (string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for MerchantIDByUserID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRefundRepository_MerchantIDByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantIDByUserID'
type MockIRefundRepository_MerchantIDByUserID_Call struct {
	*mock.Call
}

// MerchantIDByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockIRefundRepository_Expecter) MerchantIDByUserID(userID interface{}) *MockIRefundRepository_MerchantIDByUserID_Call {
	return &MockIRefundRepository_MerchantIDByUserID_Call{Call: _e.mock.On("MerchantIDByUserID", userID)}
}

func (_c *MockIRefundRepository_MerchantIDByUserID_Call) Run(run func(userID string)) *MockIRefundRepository_MerchantIDByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRefundRepository_MerchantIDByUserID_Call) Return(s string, err error) *MockIRefundRepository_MerchantIDByUserID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIRefundRepository_MerchantIDByUserID_Call) RunAndReturn(run func(userID string) (string, error)) *MockIRefundRepository_MerchantIDByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessRefund provides a mock function for the type MockIRefundRepository
func (_mock *MockIRefundRepository) ProcessRefund(refundID string, nextStatus entity.RefundStatus) (entity.Refund, entity0.Merchant, error) {
	ret := _mock.Called(refundID, nextStatus)

	if len(ret) == 0 {
		panic("no return value specified for ProcessRefund")
	}

	var r0 entity.Refund
	var r1 entity0.Merchant
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, entity.RefundStatus) (entity.Refund, entity0.Merchant, error)); ok {
		return returnFunc(refundID, nextStatus)
	}
	if returnFunc, ok := ret.Get(0).(func(string, entity.RefundStatus) entity.Refund); ok {
		r0 = returnFunc(refundID, nextStatus)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}
	if returnFunc, ok := ret.Get(1).(func(string, entity.RefundStatus) entity0.Merchant); ok {
		r1 = returnFunc(refundID, nextStatus)
	} else {
		r1 = ret.Get(1).(entity0.Merchant)
	}
	if returnFunc, ok := ret.Get(2).(func(string, entity.RefundStatus) error); ok {
		r2 = returnFunc(refundID, nextStatus)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIRefundRepository_ProcessRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessRefund'
type MockIRefundRepository_ProcessRefund_Call struct {
	*mock.Call
}

// ProcessRefund is a helper method to define mock.On call
//   - refundID string
//   - nextStatus entity.RefundStatus
func (_e *MockIRefundRepository_Expecter) ProcessRefund(refundID interface{}, nextStatus interface{}) *MockIRefundRepository_ProcessRefund_Call {
	return &MockIRefundRepository_ProcessRefund_Call{Call: _e.mock.On("ProcessRefund", refundID, nextStatus)}
}

func (_c *MockIRefundRepository_ProcessRefund_Call) Run(run func(refundID string, nextStatus entity.RefundStatus)) *MockIRefundRepository_ProcessRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 entity.RefundStatus
		if args[1] != nil {
			arg1 = args[1].(entity.RefundStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRefundRepository_ProcessRefund_Call) Return(refund entity.Refund, merchant entity0.Merchant, err error) *MockIRefundRepository_ProcessRefund_Call {
	_c.Call.Return(refund, merchant, err)
	return _c
}

func (_c *MockIRefundRepository_ProcessRefund_Call) RunAndReturn(run func(refundID string, nextStatus entity.RefundStatus) (entity.Refund, entity0.Merchant, error)) *MockIRefundRepository_ProcessRefund_Call {
	_c.Call.Return(run)
	return _c
}

// RequestRefund provides a mock function for the type MockIRefundRepository
func (_mock *MockIRefundRepository) RequestRefund(merchantID string, paymentIntentID string, reason string) (entity.Refund, error) {
	ret := _mock.Called(merchantID, paymentIntentID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RequestRefund")
	}

	var r0 entity.Refund
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (entity.Refund, error)); ok {
		return returnFunc(merchantID, paymentIntentID, reason)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) entity.Refund); ok {
		r0 = returnFunc(merchantID, paymentIntentID, reason)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(merchantID, paymentIntentID, reason)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRefundRepository_RequestRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestRefund'
type MockIRefundRepository_RequestRefund_Call struct {
	*mock.Call
}

// RequestRefund is a helper method to define mock.On call
//   - merchantID string
//   - paymentIntentID string
//   - reason string
func (_e *MockIRefundRepository_Expecter) RequestRefund(merchantID interface{}, paymentIntentID interface{}, reason interface{}) *MockIRefundRepository_RequestRefund_Call {
	return &MockIRefundRepository_RequestRefund_Call{Call: _e.mock.On("RequestRefund", merchantID, paymentIntentID, reason)}
}

func (_c *MockIRefundRepository_RequestRefund_Call) Run(run func(merchantID string, paymentIntentID string, reason string)) *MockIRefundRepository_RequestRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIRefundRepository_RequestRefund_Call) Return(refund entity.Refund, err error) *MockIRefundRepository_RequestRefund_Call {
	_c.Call.Return(refund, err)
	return _c
}

func (_c *MockIRefundRepository_RequestRefund_Call) RunAndReturn(run func(merchantID string, paymentIntentID string, reason string) (entity.Refund, error)) *MockIRefundRepository_RequestRefund_Call {
	_c.Call.Return(run)
	return _c
}

// ReviewRefund provides a mock function for the type MockIRefundRepository
func (_mock *MockIRefundRepository) ReviewRefund(refundID string, approved bool) (entity.Refund, error) {
	ret := _mock.Called(refundID, approved)

	if len(ret) == 0 {
		panic("no return value specified for ReviewRefund")
	}

	var r0 entity.Refund
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) (entity.Refund, error)); ok {
		return returnFunc(refundID, approved)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) entity.Refund); ok {
		r0 = returnFunc(refundID, approved)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(refundID, approved)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRefundRepository_ReviewRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReviewRefund'
type MockIRefundRepository_ReviewRefund_Call struct {
	*mock.Call
}

// ReviewRefund is a helper method to define mock.On call
//   - refundID string
//   - approved bool
func (_e *MockIRefundRepository_Expecter) ReviewRefund(refundID interface{}, approved interface{}) *MockIRefundRepository_ReviewRefund_Call {
	return &MockIRefundRepository_ReviewRefund_Call{Call: _e.mock.On("ReviewRefund", refundID, approved)}
}

func (_c *MockIRefundRepository_ReviewRefund_Call) Run(run func(refundID string, approved bool)) *MockIRefundRepository_ReviewRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRefundRepository_ReviewRefund_Call) Return(refund entity.Refund, err error) *MockIRefundRepository_ReviewRefund_Call {
	_c.Call.Return(refund, err)
	return _c
}

func (_c *MockIRefundRepository_ReviewRefund_Call) RunAndReturn(run func(refundID string, approved bool) (entity.Refund, error)) *MockIRefundRepository_ReviewRefund_Call {
	_c.Call.Return(run)
	return _c
}
