// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/refund/models/entity"
	modelsentity "payment-sandbox/app/modules/wallet/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockRefundRepository is an autogenerated mock type for the RefundRepository type
type MockRefundRepository struct {
	mock.Mock
}

type MockRefundRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefundRepository) EXPECT() *MockRefundRepository_Expecter {
	return &MockRefundRepository_Expecter{mock: &_m.Mock}
}

// ListRefunds provides a mock function with given fields: status
func (_m *MockRefundRepository) ListRefunds(status string) []entity.Refund {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for ListRefunds")
	}

	var r0 []entity.Refund
	if rf, ok := ret.Get(0).(func(string) []entity.Refund); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Refund)
		}
	}

	return r0
}

// MockRefundRepository_ListRefunds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRefunds'
type MockRefundRepository_ListRefunds_Call struct {
	*mock.Call
}

// ListRefunds is a helper method to define mock.On call
//   - status string
func (_e *MockRefundRepository_Expecter) ListRefunds(status interface{}) *MockRefundRepository_ListRefunds_Call {
	return &MockRefundRepository_ListRefunds_Call{Call: _e.mock.On("ListRefunds", status)}
}

func (_c *MockRefundRepository_ListRefunds_Call) Run(run func(status string)) *MockRefundRepository_ListRefunds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRefundRepository_ListRefunds_Call) Return(_a0 []entity.Refund) *MockRefundRepository_ListRefunds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefundRepository_ListRefunds_Call) RunAndReturn(run func(string) []entity.Refund) *MockRefundRepository_ListRefunds_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantIDByUserID provides a mock function with given fields: userID
func (_m *MockRefundRepository) MerchantIDByUserID(userID string) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for MerchantIDByUserID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefundRepository_MerchantIDByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantIDByUserID'
type MockRefundRepository_MerchantIDByUserID_Call struct {
	*mock.Call
}

// MerchantIDByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockRefundRepository_Expecter) MerchantIDByUserID(userID interface{}) *MockRefundRepository_MerchantIDByUserID_Call {
	return &MockRefundRepository_MerchantIDByUserID_Call{Call: _e.mock.On("MerchantIDByUserID", userID)}
}

func (_c *MockRefundRepository_MerchantIDByUserID_Call) Run(run func(userID string)) *MockRefundRepository_MerchantIDByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRefundRepository_MerchantIDByUserID_Call) Return(_a0 string, _a1 error) *MockRefundRepository_MerchantIDByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefundRepository_MerchantIDByUserID_Call) RunAndReturn(run func(string) (string, error)) *MockRefundRepository_MerchantIDByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessRefund provides a mock function with given fields: refundID, nextStatus
func (_m *MockRefundRepository) ProcessRefund(refundID string, nextStatus entity.RefundStatus) (entity.Refund, modelsentity.Merchant, error) {
	ret := _m.Called(refundID, nextStatus)

	if len(ret) == 0 {
		panic("no return value specified for ProcessRefund")
	}

	var r0 entity.Refund
	var r1 modelsentity.Merchant
	var r2 error
	if rf, ok := ret.Get(0).(func(string, entity.RefundStatus) (entity.Refund, modelsentity.Merchant, error)); ok {
		return rf(refundID, nextStatus)
	}
	if rf, ok := ret.Get(0).(func(string, entity.RefundStatus) entity.Refund); ok {
		r0 = rf(refundID, nextStatus)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, entity.RefundStatus) modelsentity.Merchant); ok {
		r1 = rf(refundID, nextStatus)
	} else {
		r1 = ret.Get(1).(modelsentity.Merchant)
	}

	if rf, ok := ret.Get(2).(func(string, entity.RefundStatus) error); ok {
		r2 = rf(refundID, nextStatus)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRefundRepository_ProcessRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessRefund'
type MockRefundRepository_ProcessRefund_Call struct {
	*mock.Call
}

// ProcessRefund is a helper method to define mock.On call
//   - refundID string
//   - nextStatus entity.RefundStatus
func (_e *MockRefundRepository_Expecter) ProcessRefund(refundID interface{}, nextStatus interface{}) *MockRefundRepository_ProcessRefund_Call {
	return &MockRefundRepository_ProcessRefund_Call{Call: _e.mock.On("ProcessRefund", refundID, nextStatus)}
}

func (_c *MockRefundRepository_ProcessRefund_Call) Run(run func(refundID string, nextStatus entity.RefundStatus)) *MockRefundRepository_ProcessRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(entity.RefundStatus))
	})
	return _c
}

func (_c *MockRefundRepository_ProcessRefund_Call) Return(_a0 entity.Refund, _a1 modelsentity.Merchant, _a2 error) *MockRefundRepository_ProcessRefund_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRefundRepository_ProcessRefund_Call) RunAndReturn(run func(string, entity.RefundStatus) (entity.Refund, modelsentity.Merchant, error)) *MockRefundRepository_ProcessRefund_Call {
	_c.Call.Return(run)
	return _c
}

// RequestRefund provides a mock function with given fields: merchantID, paymentIntentID, reason
func (_m *MockRefundRepository) RequestRefund(merchantID string, paymentIntentID string, reason string) (entity.Refund, error) {
	ret := _m.Called(merchantID, paymentIntentID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RequestRefund")
	}

	var r0 entity.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (entity.Refund, error)); ok {
		return rf(merchantID, paymentIntentID, reason)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) entity.Refund); ok {
		r0 = rf(merchantID, paymentIntentID, reason)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(merchantID, paymentIntentID, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefundRepository_RequestRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestRefund'
type MockRefundRepository_RequestRefund_Call struct {
	*mock.Call
}

// RequestRefund is a helper method to define mock.On call
//   - merchantID string
//   - paymentIntentID string
//   - reason string
func (_e *MockRefundRepository_Expecter) RequestRefund(merchantID interface{}, paymentIntentID interface{}, reason interface{}) *MockRefundRepository_RequestRefund_Call {
	return &MockRefundRepository_RequestRefund_Call{Call: _e.mock.On("RequestRefund", merchantID, paymentIntentID, reason)}
}

func (_c *MockRefundRepository_RequestRefund_Call) Run(run func(merchantID string, paymentIntentID string, reason string)) *MockRefundRepository_RequestRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRefundRepository_RequestRefund_Call) Return(_a0 entity.Refund, _a1 error) *MockRefundRepository_RequestRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefundRepository_RequestRefund_Call) RunAndReturn(run func(string, string, string) (entity.Refund, error)) *MockRefundRepository_RequestRefund_Call {
	_c.Call.Return(run)
	return _c
}

// ReviewRefund provides a mock function with given fields: refundID, approved
func (_m *MockRefundRepository) ReviewRefund(refundID string, approved bool) (entity.Refund, error) {
	ret := _m.Called(refundID, approved)

	if len(ret) == 0 {
		panic("no return value specified for ReviewRefund")
	}

	var r0 entity.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) (entity.Refund, error)); ok {
		return rf(refundID, approved)
	}
	if rf, ok := ret.Get(0).(func(string, bool) entity.Refund); ok {
		r0 = rf(refundID, approved)
	} else {
		r0 = ret.Get(0).(entity.Refund)
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(refundID, approved)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefundRepository_ReviewRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReviewRefund'
type MockRefundRepository_ReviewRefund_Call struct {
	*mock.Call
}

// ReviewRefund is a helper method to define mock.On call
//   - refundID string
//   - approved bool
func (_e *MockRefundRepository_Expecter) ReviewRefund(refundID interface{}, approved interface{}) *MockRefundRepository_ReviewRefund_Call {
	return &MockRefundRepository_ReviewRefund_Call{Call: _e.mock.On("ReviewRefund", refundID, approved)}
}

func (_c *MockRefundRepository_ReviewRefund_Call) Run(run func(refundID string, approved bool)) *MockRefundRepository_ReviewRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockRefundRepository_ReviewRefund_Call) Return(_a0 entity.Refund, _a1 error) *MockRefundRepository_ReviewRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefundRepository_ReviewRefund_Call) RunAndReturn(run func(string, bool) (entity.Refund, error)) *MockRefundRepository_ReviewRefund_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefundRepository creates a new instance of MockRefundRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefundRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefundRepository {
	mock := &MockRefundRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
