// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	entity0 "payment-sandbox/app/modules/invoice/models/entity"
	"payment-sandbox/app/modules/payment/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIPaymentService creates a new instance of MockIPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPaymentService {
	mock := &MockIPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPaymentService is an autogenerated mock type for the IPaymentService type
type MockIPaymentService struct {
	mock.Mock
}

type MockIPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPaymentService) EXPECT() *MockIPaymentService_Expecter {
	return &MockIPaymentService_Expecter{mock: &_m.Mock}
}

// CreatePaymentIntent provides a mock function for the type MockIPaymentService
func (_mock *MockIPaymentService) CreatePaymentIntent(token string, method string) (entity.PaymentIntent, entity0.Invoice, error) {
	ret := _mock.Called(token, method)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentIntent")
	}

	var r0 entity.PaymentIntent
	var r1 entity0.Invoice
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (entity.PaymentIntent, entity0.Invoice, error)); ok {
		return returnFunc(token, method)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) entity.PaymentIntent); ok {
		r0 = returnFunc(token, method)
	} else {
		r0 = ret.Get(0).(entity.PaymentIntent)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) entity0.Invoice); ok {
		r1 = returnFunc(token, method)
	} else {
		r1 = ret.Get(1).(entity0.Invoice)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(token, method)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIPaymentService_CreatePaymentIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentIntent'
type MockIPaymentService_CreatePaymentIntent_Call struct {
	*mock.Call
}

// CreatePaymentIntent is a helper method to define mock.On call
//   - token string
//   - method string
func (_e *MockIPaymentService_Expecter) CreatePaymentIntent(token interface{}, method interface{}) *MockIPaymentService_CreatePaymentIntent_Call {
	return &MockIPaymentService_CreatePaymentIntent_Call{Call: _e.mock.On("CreatePaymentIntent", token, method)}
}

func (_c *MockIPaymentService_CreatePaymentIntent_Call) Run(run func(token string, method string)) *MockIPaymentService_CreatePaymentIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPaymentService_CreatePaymentIntent_Call) Return(paymentIntent entity.PaymentIntent, invoice entity0.Invoice, err error) *MockIPaymentService_CreatePaymentIntent_Call {
	_c.Call.Return(paymentIntent, invoice, err)
	return _c
}

func (_c *MockIPaymentService_CreatePaymentIntent_Call) RunAndReturn(run func(token string, method string) (entity.PaymentIntent, entity0.Invoice, error)) *MockIPaymentService_CreatePaymentIntent_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaymentIntents provides a mock function for the type MockIPaymentService
func (_mock *MockIPaymentService) ListPaymentIntents(status string) []entity.PaymentIntent {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for ListPaymentIntents")
	}

	var r0 []entity.PaymentIntent
	if returnFunc, ok := ret.Get(0).(func(string) []entity.PaymentIntent); ok {
		r0 = returnFunc(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PaymentIntent)
		}
	}
	return r0
}

// MockIPaymentService_ListPaymentIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaymentIntents'
type MockIPaymentService_ListPaymentIntents_Call struct {
	*mock.Call
}

// ListPaymentIntents is a helper method to define mock.On call
//   - status string
func (_e *MockIPaymentService_Expecter) ListPaymentIntents(status interface{}) *MockIPaymentService_ListPaymentIntents_Call {
	return &MockIPaymentService_ListPaymentIntents_Call{Call: _e.mock.On("ListPaymentIntents", status)}
}

func (_c *MockIPaymentService_ListPaymentIntents_Call) Run(run func(status string)) *MockIPaymentService_ListPaymentIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPaymentService_ListPaymentIntents_Call) Return(paymentIntents []entity.PaymentIntent) *MockIPaymentService_ListPaymentIntents_Call {
	_c.Call.Return(paymentIntents)
	return _c
}

func (_c *MockIPaymentService_ListPaymentIntents_Call) RunAndReturn(run func(status string) []entity.PaymentIntent) *MockIPaymentService_ListPaymentIntents_Call {
	_c.Call.Return(run)
	return _c
}

// PublicInvoiceByToken provides a mock function for the type MockIPaymentService
func (_mock *MockIPaymentService) PublicInvoiceByToken(token string) (entity0.Invoice, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for PublicInvoiceByToken")
	}

	var r0 entity0.Invoice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (entity0.Invoice, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) entity0.Invoice); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(entity0.Invoice)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPaymentService_PublicInvoiceByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicInvoiceByToken'
type MockIPaymentService_PublicInvoiceByToken_Call struct {
	*mock.Call
}

// PublicInvoiceByToken is a helper method to define mock.On call
//   - token string
func (_e *MockIPaymentService_Expecter) PublicInvoiceByToken(token interface{}) *MockIPaymentService_PublicInvoiceByToken_Call {
	return &MockIPaymentService_PublicInvoiceByToken_Call{Call: _e.mock.On("PublicInvoiceByToken", token)}
}

func (_c *MockIPaymentService_PublicInvoiceByToken_Call) Run(run func(token string)) *MockIPaymentService_PublicInvoiceByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPaymentService_PublicInvoiceByToken_Call) Return(invoice entity0.Invoice, err error) *MockIPaymentService_PublicInvoiceByToken_Call {
	_c.Call.Return(invoice, err)
	return _c
}

func (_c *MockIPaymentService_PublicInvoiceByToken_Call) RunAndReturn(run func(token string) (entity0.Invoice, error)) *MockIPaymentService_PublicInvoiceByToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentIntentStatus provides a mock function for the type MockIPaymentService
func (_mock *MockIPaymentService) UpdatePaymentIntentStatus(paymentID string, status string) (entity.PaymentIntent, entity0.Invoice, error) {
	ret := _mock.Called(paymentID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentIntentStatus")
	}

	var r0 entity.PaymentIntent
	var r1 entity0.Invoice
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (entity.PaymentIntent, entity0.Invoice, error)); ok {
		return returnFunc(paymentID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) entity.PaymentIntent); ok {
		r0 = returnFunc(paymentID, status)
	} else {
		r0 = ret.Get(0).(entity.PaymentIntent)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) entity0.Invoice); ok {
		r1 = returnFunc(paymentID, status)
	} else {
		r1 = ret.Get(1).(entity0.Invoice)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(paymentID, status)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIPaymentService_UpdatePaymentIntentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentIntentStatus'
type MockIPaymentService_UpdatePaymentIntentStatus_Call struct {
	*mock.Call
}

// UpdatePaymentIntentStatus is a helper method to define mock.On call
//   - paymentID string
//   - status string
func (_e *MockIPaymentService_Expecter) UpdatePaymentIntentStatus(paymentID interface{}, status interface{}) *MockIPaymentService_UpdatePaymentIntentStatus_Call {
	return &MockIPaymentService_UpdatePaymentIntentStatus_Call{Call: _e.mock.On("UpdatePaymentIntentStatus", paymentID, status)}
}

func (_c *MockIPaymentService_UpdatePaymentIntentStatus_Call) Run(run func(paymentID string, status string)) *MockIPaymentService_UpdatePaymentIntentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPaymentService_UpdatePaymentIntentStatus_Call) Return(paymentIntent entity.PaymentIntent, invoice entity0.Invoice, err error) *MockIPaymentService_UpdatePaymentIntentStatus_Call {
	_c.Call.Return(paymentIntent, invoice, err)
	return _c
}

func (_c *MockIPaymentService_UpdatePaymentIntentStatus_Call) RunAndReturn(run func(paymentID string, status string) (entity.PaymentIntent, entity0.Invoice, error)) *MockIPaymentService_UpdatePaymentIntentStatus_Call {
	_c.Call.Return(run)
	return _c
}
