// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/auth/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockIAuthRepository is an autogenerated mock type for the IAuthRepository type
type MockIAuthRepository struct {
	mock.Mock
}

type MockIAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAuthRepository) EXPECT() *MockIAuthRepository_Expecter {
	return &MockIAuthRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: name, email, passwordHash, role
func (_m *MockIAuthRepository) CreateUser(name string, email string, passwordHash string, role entity.Role) (entity.User, error) {
	ret := _m.Called(name, email, passwordHash, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, entity.Role) (entity.User, error)); ok {
		return rf(name, email, passwordHash, role)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, entity.Role) entity.User); ok {
		r0 = rf(name, email, passwordHash, role)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, entity.Role) error); ok {
		r1 = rf(name, email, passwordHash, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAuthRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIAuthRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - name string
//   - email string
//   - passwordHash string
//   - role entity.Role
func (_e *MockIAuthRepository_Expecter) CreateUser(name interface{}, email interface{}, passwordHash interface{}, role interface{}) *MockIAuthRepository_CreateUser_Call {
	return &MockIAuthRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", name, email, passwordHash, role)}
}

func (_c *MockIAuthRepository_CreateUser_Call) Run(run func(name string, email string, passwordHash string, role entity.Role)) *MockIAuthRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(entity.Role))
	})
	return _c
}

func (_c *MockIAuthRepository_CreateUser_Call) Return(_a0 entity.User, _a1 error) *MockIAuthRepository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAuthRepository_CreateUser_Call) RunAndReturn(run func(string, string, string, entity.Role) (entity.User, error)) *MockIAuthRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureAdminSeed provides a mock function with no fields
func (_m *MockIAuthRepository) EnsureAdminSeed() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnsureAdminSeed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAuthRepository_EnsureAdminSeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureAdminSeed'
type MockIAuthRepository_EnsureAdminSeed_Call struct {
	*mock.Call
}

// EnsureAdminSeed is a helper method to define mock.On call
func (_e *MockIAuthRepository_Expecter) EnsureAdminSeed() *MockIAuthRepository_EnsureAdminSeed_Call {
	return &MockIAuthRepository_EnsureAdminSeed_Call{Call: _e.mock.On("EnsureAdminSeed")}
}

func (_c *MockIAuthRepository_EnsureAdminSeed_Call) Run(run func()) *MockIAuthRepository_EnsureAdminSeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIAuthRepository_EnsureAdminSeed_Call) Return(_a0 error) *MockIAuthRepository_EnsureAdminSeed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAuthRepository_EnsureAdminSeed_Call) RunAndReturn(run func() error) *MockIAuthRepository_EnsureAdminSeed_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function with given fields: email
func (_m *MockIAuthRepository) FindUserByEmail(email string) (entity.User, bool) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 entity.User
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (entity.User, bool)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) entity.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockIAuthRepository_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockIAuthRepository_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockIAuthRepository_Expecter) FindUserByEmail(email interface{}) *MockIAuthRepository_FindUserByEmail_Call {
	return &MockIAuthRepository_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", email)}
}

func (_c *MockIAuthRepository_FindUserByEmail_Call) Run(run func(email string)) *MockIAuthRepository_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIAuthRepository_FindUserByEmail_Call) Return(_a0 entity.User, _a1 bool) *MockIAuthRepository_FindUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAuthRepository_FindUserByEmail_Call) RunAndReturn(run func(string) (entity.User, bool)) *MockIAuthRepository_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAuthRepository creates a new instance of MockIAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAuthRepository {
	mock := &MockIAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
