// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/wallet/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockIWalletService is an autogenerated mock type for the IWalletService type
type MockIWalletService struct {
	mock.Mock
}

type MockIWalletService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIWalletService) EXPECT() *MockIWalletService_Expecter {
	return &MockIWalletService_Expecter{mock: &_m.Mock}
}

// CreateTopup provides a mock function with given fields: userID, amount
func (_m *MockIWalletService) CreateTopup(userID string, amount float64) (entity.Topup, error) {
	ret := _m.Called(userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for CreateTopup")
	}

	var r0 entity.Topup
	var r1 error
	if rf, ok := ret.Get(0).(func(string, float64) (entity.Topup, error)); ok {
		return rf(userID, amount)
	}
	if rf, ok := ret.Get(0).(func(string, float64) entity.Topup); ok {
		r0 = rf(userID, amount)
	} else {
		r0 = ret.Get(0).(entity.Topup)
	}

	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(userID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIWalletService_CreateTopup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTopup'
type MockIWalletService_CreateTopup_Call struct {
	*mock.Call
}

// CreateTopup is a helper method to define mock.On call
//   - userID string
//   - amount float64
func (_e *MockIWalletService_Expecter) CreateTopup(userID interface{}, amount interface{}) *MockIWalletService_CreateTopup_Call {
	return &MockIWalletService_CreateTopup_Call{Call: _e.mock.On("CreateTopup", userID, amount)}
}

func (_c *MockIWalletService_CreateTopup_Call) Run(run func(userID string, amount float64)) *MockIWalletService_CreateTopup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64))
	})
	return _c
}

func (_c *MockIWalletService_CreateTopup_Call) Return(_a0 entity.Topup, _a1 error) *MockIWalletService_CreateTopup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIWalletService_CreateTopup_Call) RunAndReturn(run func(string, float64) (entity.Topup, error)) *MockIWalletService_CreateTopup_Call {
	_c.Call.Return(run)
	return _c
}

// ListTopups provides a mock function with no fields
func (_m *MockIWalletService) ListTopups() []entity.Topup {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListTopups")
	}

	var r0 []entity.Topup
	if rf, ok := ret.Get(0).(func() []entity.Topup); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Topup)
		}
	}

	return r0
}

// MockIWalletService_ListTopups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTopups'
type MockIWalletService_ListTopups_Call struct {
	*mock.Call
}

// ListTopups is a helper method to define mock.On call
func (_e *MockIWalletService_Expecter) ListTopups() *MockIWalletService_ListTopups_Call {
	return &MockIWalletService_ListTopups_Call{Call: _e.mock.On("ListTopups")}
}

func (_c *MockIWalletService_ListTopups_Call) Run(run func()) *MockIWalletService_ListTopups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIWalletService_ListTopups_Call) Return(_a0 []entity.Topup) *MockIWalletService_ListTopups_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIWalletService_ListTopups_Call) RunAndReturn(run func() []entity.Topup) *MockIWalletService_ListTopups_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTopupStatus provides a mock function with given fields: topupID, status
func (_m *MockIWalletService) UpdateTopupStatus(topupID string, status string) (entity.Topup, error) {
	ret := _m.Called(topupID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTopupStatus")
	}

	var r0 entity.Topup
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.Topup, error)); ok {
		return rf(topupID, status)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.Topup); ok {
		r0 = rf(topupID, status)
	} else {
		r0 = ret.Get(0).(entity.Topup)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(topupID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIWalletService_UpdateTopupStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTopupStatus'
type MockIWalletService_UpdateTopupStatus_Call struct {
	*mock.Call
}

// UpdateTopupStatus is a helper method to define mock.On call
//   - topupID string
//   - status string
func (_e *MockIWalletService_Expecter) UpdateTopupStatus(topupID interface{}, status interface{}) *MockIWalletService_UpdateTopupStatus_Call {
	return &MockIWalletService_UpdateTopupStatus_Call{Call: _e.mock.On("UpdateTopupStatus", topupID, status)}
}

func (_c *MockIWalletService_UpdateTopupStatus_Call) Run(run func(topupID string, status string)) *MockIWalletService_UpdateTopupStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIWalletService_UpdateTopupStatus_Call) Return(_a0 entity.Topup, _a1 error) *MockIWalletService_UpdateTopupStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIWalletService_UpdateTopupStatus_Call) RunAndReturn(run func(string, string) (entity.Topup, error)) *MockIWalletService_UpdateTopupStatus_Call {
	_c.Call.Return(run)
	return _c
}

// WalletByUserID provides a mock function with given fields: userID
func (_m *MockIWalletService) WalletByUserID(userID string) (entity.Merchant, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for WalletByUserID")
	}

	var r0 entity.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entity.Merchant, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) entity.Merchant); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(entity.Merchant)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIWalletService_WalletByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalletByUserID'
type MockIWalletService_WalletByUserID_Call struct {
	*mock.Call
}

// WalletByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockIWalletService_Expecter) WalletByUserID(userID interface{}) *MockIWalletService_WalletByUserID_Call {
	return &MockIWalletService_WalletByUserID_Call{Call: _e.mock.On("WalletByUserID", userID)}
}

func (_c *MockIWalletService_WalletByUserID_Call) Run(run func(userID string)) *MockIWalletService_WalletByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIWalletService_WalletByUserID_Call) Return(_a0 entity.Merchant, _a1 error) *MockIWalletService_WalletByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIWalletService_WalletByUserID_Call) RunAndReturn(run func(string) (entity.Merchant, error)) *MockIWalletService_WalletByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIWalletService creates a new instance of MockIWalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIWalletService {
	mock := &MockIWalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
