// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/payment/models/entity"

	modelsentity "payment-sandbox/app/modules/invoice/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentService is an autogenerated mock type for the PaymentService type
type MockPaymentService struct {
	mock.Mock
}

type MockPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentService) EXPECT() *MockPaymentService_Expecter {
	return &MockPaymentService_Expecter{mock: &_m.Mock}
}

// CreatePaymentIntent provides a mock function with given fields: token, method
func (_m *MockPaymentService) CreatePaymentIntent(token string, method string) (entity.PaymentIntent, modelsentity.Invoice, error) {
	ret := _m.Called(token, method)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentIntent")
	}

	var r0 entity.PaymentIntent
	var r1 modelsentity.Invoice
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.PaymentIntent, modelsentity.Invoice, error)); ok {
		return rf(token, method)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.PaymentIntent); ok {
		r0 = rf(token, method)
	} else {
		r0 = ret.Get(0).(entity.PaymentIntent)
	}

	if rf, ok := ret.Get(1).(func(string, string) modelsentity.Invoice); ok {
		r1 = rf(token, method)
	} else {
		r1 = ret.Get(1).(modelsentity.Invoice)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(token, method)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPaymentService_CreatePaymentIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentIntent'
type MockPaymentService_CreatePaymentIntent_Call struct {
	*mock.Call
}

// CreatePaymentIntent is a helper method to define mock.On call
//   - token string
//   - method string
func (_e *MockPaymentService_Expecter) CreatePaymentIntent(token interface{}, method interface{}) *MockPaymentService_CreatePaymentIntent_Call {
	return &MockPaymentService_CreatePaymentIntent_Call{Call: _e.mock.On("CreatePaymentIntent", token, method)}
}

func (_c *MockPaymentService_CreatePaymentIntent_Call) Run(run func(token string, method string)) *MockPaymentService_CreatePaymentIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentService_CreatePaymentIntent_Call) Return(_a0 entity.PaymentIntent, _a1 modelsentity.Invoice, _a2 error) *MockPaymentService_CreatePaymentIntent_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPaymentService_CreatePaymentIntent_Call) RunAndReturn(run func(string, string) (entity.PaymentIntent, modelsentity.Invoice, error)) *MockPaymentService_CreatePaymentIntent_Call {
	_c.Call.Return(run)
	return _c
}

// ListPaymentIntents provides a mock function with given fields: status
func (_m *MockPaymentService) ListPaymentIntents(status string) []entity.PaymentIntent {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for ListPaymentIntents")
	}

	var r0 []entity.PaymentIntent
	if rf, ok := ret.Get(0).(func(string) []entity.PaymentIntent); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PaymentIntent)
		}
	}

	return r0
}

// MockPaymentService_ListPaymentIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPaymentIntents'
type MockPaymentService_ListPaymentIntents_Call struct {
	*mock.Call
}

// ListPaymentIntents is a helper method to define mock.On call
//   - status string
func (_e *MockPaymentService_Expecter) ListPaymentIntents(status interface{}) *MockPaymentService_ListPaymentIntents_Call {
	return &MockPaymentService_ListPaymentIntents_Call{Call: _e.mock.On("ListPaymentIntents", status)}
}

func (_c *MockPaymentService_ListPaymentIntents_Call) Run(run func(status string)) *MockPaymentService_ListPaymentIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPaymentService_ListPaymentIntents_Call) Return(_a0 []entity.PaymentIntent) *MockPaymentService_ListPaymentIntents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentService_ListPaymentIntents_Call) RunAndReturn(run func(string) []entity.PaymentIntent) *MockPaymentService_ListPaymentIntents_Call {
	_c.Call.Return(run)
	return _c
}

// PublicInvoiceByToken provides a mock function with given fields: token
func (_m *MockPaymentService) PublicInvoiceByToken(token string) (modelsentity.Invoice, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for PublicInvoiceByToken")
	}

	var r0 modelsentity.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (modelsentity.Invoice, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) modelsentity.Invoice); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(modelsentity.Invoice)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentService_PublicInvoiceByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicInvoiceByToken'
type MockPaymentService_PublicInvoiceByToken_Call struct {
	*mock.Call
}

// PublicInvoiceByToken is a helper method to define mock.On call
//   - token string
func (_e *MockPaymentService_Expecter) PublicInvoiceByToken(token interface{}) *MockPaymentService_PublicInvoiceByToken_Call {
	return &MockPaymentService_PublicInvoiceByToken_Call{Call: _e.mock.On("PublicInvoiceByToken", token)}
}

func (_c *MockPaymentService_PublicInvoiceByToken_Call) Run(run func(token string)) *MockPaymentService_PublicInvoiceByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPaymentService_PublicInvoiceByToken_Call) Return(_a0 modelsentity.Invoice, _a1 error) *MockPaymentService_PublicInvoiceByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentService_PublicInvoiceByToken_Call) RunAndReturn(run func(string) (modelsentity.Invoice, error)) *MockPaymentService_PublicInvoiceByToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentIntentStatus provides a mock function with given fields: paymentID, status
func (_m *MockPaymentService) UpdatePaymentIntentStatus(paymentID string, status string) (entity.PaymentIntent, modelsentity.Invoice, error) {
	ret := _m.Called(paymentID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentIntentStatus")
	}

	var r0 entity.PaymentIntent
	var r1 modelsentity.Invoice
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (entity.PaymentIntent, modelsentity.Invoice, error)); ok {
		return rf(paymentID, status)
	}
	if rf, ok := ret.Get(0).(func(string, string) entity.PaymentIntent); ok {
		r0 = rf(paymentID, status)
	} else {
		r0 = ret.Get(0).(entity.PaymentIntent)
	}

	if rf, ok := ret.Get(1).(func(string, string) modelsentity.Invoice); ok {
		r1 = rf(paymentID, status)
	} else {
		r1 = ret.Get(1).(modelsentity.Invoice)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(paymentID, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPaymentService_UpdatePaymentIntentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentIntentStatus'
type MockPaymentService_UpdatePaymentIntentStatus_Call struct {
	*mock.Call
}

// UpdatePaymentIntentStatus is a helper method to define mock.On call
//   - paymentID string
//   - status string
func (_e *MockPaymentService_Expecter) UpdatePaymentIntentStatus(paymentID interface{}, status interface{}) *MockPaymentService_UpdatePaymentIntentStatus_Call {
	return &MockPaymentService_UpdatePaymentIntentStatus_Call{Call: _e.mock.On("UpdatePaymentIntentStatus", paymentID, status)}
}

func (_c *MockPaymentService_UpdatePaymentIntentStatus_Call) Run(run func(paymentID string, status string)) *MockPaymentService_UpdatePaymentIntentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentService_UpdatePaymentIntentStatus_Call) Return(_a0 entity.PaymentIntent, _a1 modelsentity.Invoice, _a2 error) *MockPaymentService_UpdatePaymentIntentStatus_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPaymentService_UpdatePaymentIntentStatus_Call) RunAndReturn(run func(string, string) (entity.PaymentIntent, modelsentity.Invoice, error)) *MockPaymentService_UpdatePaymentIntentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentService creates a new instance of MockPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentService {
	mock := &MockPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
