// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/users/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockIUserService is an autogenerated mock type for the IUserService type
type MockIUserService struct {
	mock.Mock
}

type MockIUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserService) EXPECT() *MockIUserService_Expecter {
	return &MockIUserService_Expecter{mock: &_m.Mock}
}

// RegisterMerchant provides a mock function with given fields: name, email, password
func (_m *MockIUserService) RegisterMerchant(name string, email string, password string) (entity.User, error) {
	ret := _m.Called(name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterMerchant")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (entity.User, error)); ok {
		return rf(name, email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) entity.User); ok {
		r0 = rf(name, email, password)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(name, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserService_RegisterMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterMerchant'
type MockIUserService_RegisterMerchant_Call struct {
	*mock.Call
}

// RegisterMerchant is a helper method to define mock.On call
//   - name string
//   - email string
//   - password string
func (_e *MockIUserService_Expecter) RegisterMerchant(name interface{}, email interface{}, password interface{}) *MockIUserService_RegisterMerchant_Call {
	return &MockIUserService_RegisterMerchant_Call{Call: _e.mock.On("RegisterMerchant", name, email, password)}
}

func (_c *MockIUserService_RegisterMerchant_Call) Run(run func(name string, email string, password string)) *MockIUserService_RegisterMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIUserService_RegisterMerchant_Call) Return(_a0 entity.User, _a1 error) *MockIUserService_RegisterMerchant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserService_RegisterMerchant_Call) RunAndReturn(run func(string, string, string) (entity.User, error)) *MockIUserService_RegisterMerchant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUserService creates a new instance of MockIUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserService {
	mock := &MockIUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
