// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"payment-sandbox/app/shared/journeylog"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIJourneyLogger creates a new instance of MockIJourneyLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIJourneyLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIJourneyLogger {
	mock := &MockIJourneyLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIJourneyLogger is an autogenerated mock type for the IJourneyLogger type
type MockIJourneyLogger struct {
	mock.Mock
}

type MockIJourneyLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIJourneyLogger) EXPECT() *MockIJourneyLogger_Expecter {
	return &MockIJourneyLogger_Expecter{mock: &_m.Mock}
}

// Log provides a mock function for the type MockIJourneyLogger
func (_mock *MockIJourneyLogger) Log(ctx context.Context, event journeylog.Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, journeylog.Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIJourneyLogger_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockIJourneyLogger_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - ctx context.Context
//   - event journeylog.Event
func (_e *MockIJourneyLogger_Expecter) Log(ctx interface{}, event interface{}) *MockIJourneyLogger_Log_Call {
	return &MockIJourneyLogger_Log_Call{Call: _e.mock.On("Log", ctx, event)}
}

func (_c *MockIJourneyLogger_Log_Call) Run(run func(ctx context.Context, event journeylog.Event)) *MockIJourneyLogger_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 journeylog.Event
		if args[1] != nil {
			arg1 = args[1].(journeylog.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIJourneyLogger_Log_Call) Return(err error) *MockIJourneyLogger_Log_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIJourneyLogger_Log_Call) RunAndReturn(run func(ctx context.Context, event journeylog.Event) error) *MockIJourneyLogger_Log_Call {
	_c.Call.Return(run)
	return _c
}
