// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"payment-sandbox/app/modules/admin/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIAdminRepository creates a new instance of MockIAdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAdminRepository {
	mock := &MockIAdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAdminRepository is an autogenerated mock type for the IAdminRepository type
type MockIAdminRepository struct {
	mock.Mock
}

type MockIAdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAdminRepository) EXPECT() *MockIAdminRepository_Expecter {
	return &MockIAdminRepository_Expecter{mock: &_m.Mock}
}

// DashboardStats provides a mock function for the type MockIAdminRepository
func (_mock *MockIAdminRepository) DashboardStats(filter entity.StatsFilter) entity.DashboardStats {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for DashboardStats")
	}

	var r0 entity.DashboardStats
	if returnFunc, ok := ret.Get(0).(func(entity.StatsFilter) entity.DashboardStats); ok {
		r0 = returnFunc(filter)
	} else {
		r0 = ret.Get(0).(entity.DashboardStats)
	}
	return r0
}

// MockIAdminRepository_DashboardStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DashboardStats'
type MockIAdminRepository_DashboardStats_Call struct {
	*mock.Call
}

// DashboardStats is a helper method to define mock.On call
//   - filter entity.StatsFilter
func (_e *MockIAdminRepository_Expecter) DashboardStats(filter interface{}) *MockIAdminRepository_DashboardStats_Call {
	return &MockIAdminRepository_DashboardStats_Call{Call: _e.mock.On("DashboardStats", filter)}
}

func (_c *MockIAdminRepository_DashboardStats_Call) Run(run func(filter entity.StatsFilter)) *MockIAdminRepository_DashboardStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entity.StatsFilter
		if args[0] != nil {
			arg0 = args[0].(entity.StatsFilter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIAdminRepository_DashboardStats_Call) Return(dashboardStats entity.DashboardStats) *MockIAdminRepository_DashboardStats_Call {
	_c.Call.Return(dashboardStats)
	return _c
}

func (_c *MockIAdminRepository_DashboardStats_Call) RunAndReturn(run func(filter entity.StatsFilter) entity.DashboardStats) *MockIAdminRepository_DashboardStats_Call {
	_c.Call.Return(run)
	return _c
}
