// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	modelsentity "payment-sandbox/app/modules/payment/models/entity"
	entity "payment-sandbox/app/modules/wallet/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockIWalletRepository is an autogenerated mock type for the IWalletRepository type
type MockIWalletRepository struct {
	mock.Mock
}

type MockIWalletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIWalletRepository) EXPECT() *MockIWalletRepository_Expecter {
	return &MockIWalletRepository_Expecter{mock: &_m.Mock}
}

// CreateTopup provides a mock function with given fields: merchantID, amount
func (_m *MockIWalletRepository) CreateTopup(merchantID string, amount float64) (entity.Topup, error) {
	ret := _m.Called(merchantID, amount)

	if len(ret) == 0 {
		panic("no return value specified for CreateTopup")
	}

	var r0 entity.Topup
	var r1 error
	if rf, ok := ret.Get(0).(func(string, float64) (entity.Topup, error)); ok {
		return rf(merchantID, amount)
	}
	if rf, ok := ret.Get(0).(func(string, float64) entity.Topup); ok {
		r0 = rf(merchantID, amount)
	} else {
		r0 = ret.Get(0).(entity.Topup)
	}

	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(merchantID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIWalletRepository_CreateTopup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTopup'
type MockIWalletRepository_CreateTopup_Call struct {
	*mock.Call
}

// CreateTopup is a helper method to define mock.On call
//   - merchantID string
//   - amount float64
func (_e *MockIWalletRepository_Expecter) CreateTopup(merchantID interface{}, amount interface{}) *MockIWalletRepository_CreateTopup_Call {
	return &MockIWalletRepository_CreateTopup_Call{Call: _e.mock.On("CreateTopup", merchantID, amount)}
}

func (_c *MockIWalletRepository_CreateTopup_Call) Run(run func(merchantID string, amount float64)) *MockIWalletRepository_CreateTopup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64))
	})
	return _c
}

func (_c *MockIWalletRepository_CreateTopup_Call) Return(_a0 entity.Topup, _a1 error) *MockIWalletRepository_CreateTopup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIWalletRepository_CreateTopup_Call) RunAndReturn(run func(string, float64) (entity.Topup, error)) *MockIWalletRepository_CreateTopup_Call {
	_c.Call.Return(run)
	return _c
}

// GetMerchantWallet provides a mock function with given fields: userID
func (_m *MockIWalletRepository) GetMerchantWallet(userID string) (entity.Merchant, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantWallet")
	}

	var r0 entity.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entity.Merchant, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) entity.Merchant); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(entity.Merchant)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIWalletRepository_GetMerchantWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMerchantWallet'
type MockIWalletRepository_GetMerchantWallet_Call struct {
	*mock.Call
}

// GetMerchantWallet is a helper method to define mock.On call
//   - userID string
func (_e *MockIWalletRepository_Expecter) GetMerchantWallet(userID interface{}) *MockIWalletRepository_GetMerchantWallet_Call {
	return &MockIWalletRepository_GetMerchantWallet_Call{Call: _e.mock.On("GetMerchantWallet", userID)}
}

func (_c *MockIWalletRepository_GetMerchantWallet_Call) Run(run func(userID string)) *MockIWalletRepository_GetMerchantWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIWalletRepository_GetMerchantWallet_Call) Return(_a0 entity.Merchant, _a1 error) *MockIWalletRepository_GetMerchantWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIWalletRepository_GetMerchantWallet_Call) RunAndReturn(run func(string) (entity.Merchant, error)) *MockIWalletRepository_GetMerchantWallet_Call {
	_c.Call.Return(run)
	return _c
}

// ListTopups provides a mock function with no fields
func (_m *MockIWalletRepository) ListTopups() []entity.Topup {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListTopups")
	}

	var r0 []entity.Topup
	if rf, ok := ret.Get(0).(func() []entity.Topup); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Topup)
		}
	}

	return r0
}

// MockIWalletRepository_ListTopups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTopups'
type MockIWalletRepository_ListTopups_Call struct {
	*mock.Call
}

// ListTopups is a helper method to define mock.On call
func (_e *MockIWalletRepository_Expecter) ListTopups() *MockIWalletRepository_ListTopups_Call {
	return &MockIWalletRepository_ListTopups_Call{Call: _e.mock.On("ListTopups")}
}

func (_c *MockIWalletRepository_ListTopups_Call) Run(run func()) *MockIWalletRepository_ListTopups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIWalletRepository_ListTopups_Call) Return(_a0 []entity.Topup) *MockIWalletRepository_ListTopups_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIWalletRepository_ListTopups_Call) RunAndReturn(run func() []entity.Topup) *MockIWalletRepository_ListTopups_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantIDByUserID provides a mock function with given fields: userID
func (_m *MockIWalletRepository) MerchantIDByUserID(userID string) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for MerchantIDByUserID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIWalletRepository_MerchantIDByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantIDByUserID'
type MockIWalletRepository_MerchantIDByUserID_Call struct {
	*mock.Call
}

// MerchantIDByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockIWalletRepository_Expecter) MerchantIDByUserID(userID interface{}) *MockIWalletRepository_MerchantIDByUserID_Call {
	return &MockIWalletRepository_MerchantIDByUserID_Call{Call: _e.mock.On("MerchantIDByUserID", userID)}
}

func (_c *MockIWalletRepository_MerchantIDByUserID_Call) Run(run func(userID string)) *MockIWalletRepository_MerchantIDByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIWalletRepository_MerchantIDByUserID_Call) Return(_a0 string, _a1 error) *MockIWalletRepository_MerchantIDByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIWalletRepository_MerchantIDByUserID_Call) RunAndReturn(run func(string) (string, error)) *MockIWalletRepository_MerchantIDByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTopupStatus provides a mock function with given fields: topupID, nextStatus
func (_m *MockIWalletRepository) UpdateTopupStatus(topupID string, nextStatus modelsentity.PaymentStatus) (entity.Topup, error) {
	ret := _m.Called(topupID, nextStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTopupStatus")
	}

	var r0 entity.Topup
	var r1 error
	if rf, ok := ret.Get(0).(func(string, modelsentity.PaymentStatus) (entity.Topup, error)); ok {
		return rf(topupID, nextStatus)
	}
	if rf, ok := ret.Get(0).(func(string, modelsentity.PaymentStatus) entity.Topup); ok {
		r0 = rf(topupID, nextStatus)
	} else {
		r0 = ret.Get(0).(entity.Topup)
	}

	if rf, ok := ret.Get(1).(func(string, modelsentity.PaymentStatus) error); ok {
		r1 = rf(topupID, nextStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIWalletRepository_UpdateTopupStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTopupStatus'
type MockIWalletRepository_UpdateTopupStatus_Call struct {
	*mock.Call
}

// UpdateTopupStatus is a helper method to define mock.On call
//   - topupID string
//   - nextStatus modelsentity.PaymentStatus
func (_e *MockIWalletRepository_Expecter) UpdateTopupStatus(topupID interface{}, nextStatus interface{}) *MockIWalletRepository_UpdateTopupStatus_Call {
	return &MockIWalletRepository_UpdateTopupStatus_Call{Call: _e.mock.On("UpdateTopupStatus", topupID, nextStatus)}
}

func (_c *MockIWalletRepository_UpdateTopupStatus_Call) Run(run func(topupID string, nextStatus modelsentity.PaymentStatus)) *MockIWalletRepository_UpdateTopupStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(modelsentity.PaymentStatus))
	})
	return _c
}

func (_c *MockIWalletRepository_UpdateTopupStatus_Call) Return(_a0 entity.Topup, _a1 error) *MockIWalletRepository_UpdateTopupStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIWalletRepository_UpdateTopupStatus_Call) RunAndReturn(run func(string, modelsentity.PaymentStatus) (entity.Topup, error)) *MockIWalletRepository_UpdateTopupStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIWalletRepository creates a new instance of MockIWalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIWalletRepository {
	mock := &MockIWalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
