// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "payment-sandbox/app/modules/admin/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockAdminService is an autogenerated mock type for the AdminService type
type MockAdminService struct {
	mock.Mock
}

type MockAdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminService) EXPECT() *MockAdminService_Expecter {
	return &MockAdminService_Expecter{mock: &_m.Mock}
}

// Stats provides a mock function with given fields: merchantID, startDate, endDate
func (_m *MockAdminService) Stats(merchantID string, startDate string, endDate string) (entity.DashboardStats, error) {
	ret := _m.Called(merchantID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 entity.DashboardStats
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (entity.DashboardStats, error)); ok {
		return rf(merchantID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) entity.DashboardStats); ok {
		r0 = rf(merchantID, startDate, endDate)
	} else {
		r0 = ret.Get(0).(entity.DashboardStats)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(merchantID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminService_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockAdminService_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - merchantID string
//   - startDate string
//   - endDate string
func (_e *MockAdminService_Expecter) Stats(merchantID interface{}, startDate interface{}, endDate interface{}) *MockAdminService_Stats_Call {
	return &MockAdminService_Stats_Call{Call: _e.mock.On("Stats", merchantID, startDate, endDate)}
}

func (_c *MockAdminService_Stats_Call) Run(run func(merchantID string, startDate string, endDate string)) *MockAdminService_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAdminService_Stats_Call) Return(_a0 entity.DashboardStats, _a1 error) *MockAdminService_Stats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminService_Stats_Call) RunAndReturn(run func(string, string, string) (entity.DashboardStats, error)) *MockAdminService_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminService creates a new instance of MockAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminService {
	mock := &MockAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
